### ISSUE TITLE
Floating windows - mouse clicks not working

### ISSUE THREAD

**Issue by jamesmccabe** [stumpwm/stumpwm#1034]
On the latest git version of Stump when I open a floating window the mouse seems to have stopped working.
This happens in both tiling and floating groups.
I can't move or resize floating windows using left and right click.

**Comment by dvnmk** [comment]
Here also, I'm using Arch linux. 
1. stumpwm from package manager work with float but I have quicklisp problem. 
2. stumpwm-ql compiled fail.
3. stumpwm from git compiled but no mouse control possible
4. installed roswell, from roswell same compile error with case nr.2

**Comment by dvnmk** [comment]
I found a thread about this problem in nntp+news.gmane.io:gmane.comp.window-managers.stumpwm.devel
"mouse not dragging a float window" 
(setf *float-window-modifier* :meta)
Then with meta key I can move and resize floating windows. But without modifier, clicking titlebar method is still not working.

**Comment by viriuwu** [comment]
Same thing happening here. I can drag the window with the modifier, but only when clicking parts that aren't the titlebar (so the middle for example).

**Comment by jorams** [comment]
I think I might have broken this in #1017, which fixes #527 by grabbing mouse buttons on the window rather than our parent window. The border around floating windows is the parent window, so mouse events there are no longer caught. You can still move and resize windows by holding `*float-window-modifier*` (the super key by default) and holding the mouse button on the window itself.

I'm not sure how to both keep that fix and have mouse button dragging on the decoration. Maybe we should create another (transparent) window covering the decoration to capture mouse events?
