### ISSUE TITLE
Bug: Tiling IEM Multiencoder

### ISSUE THREAD

**Issue by brandflake11** [stumpwm/stumpwm#1065]
I have found a bug using the latest git version of stumpwm, compiled myself. Here is how to replicate it:

0. Install carla, IEM plugins. On arch, the packages are called: `carla iempluginsuite`
1. Start jack-enabled server (jack or pipewire with jack support. You just need it to load a plugin) You can use qjackctl to start jack.
2. Open carla (if you've never used carla, make sure to scan your system for plugins and the IEM plugins are in the right location)
3. Load the IEM Multiencoder plugin with carla
4. Open the gear icon on the newly loaded plugin of carla to launch the IEM Multiencoder plugin
5. Watch stumpwm fall to its knees trying to tile Multiencoder, hanging indefinitely

A way around this is to launch multiencoder on a floating group. However, I wanted to report this, as this is probably not something stumpwm should do. 

I hope this helps, let me know if there's anything you might want to test or if you need any more information. I am not using any modules besides :stumpwm-base16's dracula theme. I also have a mode-line enabled and have :swank and :str loaded with quicklisp (I'm not sure if that matters).

**Comment by dmb2** [comment]
We can't really help client applications that spawn a ton of windows.  Unless you've got evidence that we're mis-handling x events, everything you're describing is proper behavior.  The float-groups exist explicitly for this reason, in order to make it possible to use misbehaving programs in an adhoc way.

Feel free to reopen if I've missed something.
