### ISSUE TITLE
Adding a new head results in unscaled frame

### ISSUE THREAD

**Issue by robert-uhl** [stumpwm/stumpwm#1087]
Switching from one head to two results in a frame on the new head with the dimensions of the old. This appears to be due to a bug in [`GROUP-ADD-HEAD`](https://github.com/stumpwm/stumpwm/blob/master/tile-group.lisp#L184) in which a new frame is added to the group’s frame tree list based on the head number but then [referenced by the position of the head in the group’s head list.](https://github.com/stumpwm/stumpwm/blob/master/tile-group.lisp#L186).

This may have been triggered because the existing laptop head was numbered 5 while the external HDMI head was numbered 4, but I am not completely certain.

**Comment by tiberious726** [comment]
I just ran into this too. The numbering is just weird to stay consistent will X (eg: run xrandr). This a bug introduced by a patch that checks if the heads are actually different sizes (if the "screens" are different "resolutions") before rescaling them, and for whatever reason they are coming in the same in the configure-notify event. I want to figure why before submitting a patch, but as a quick workaround, add nil to this check:

https://github.com/stumpwm/stumpwm/blob/ffeb9eba470a3c603567c3b553a674e074071936/head.lisp#L176

I imagine it was added for `group-before-resize-head` and `group-before-resize-head` (I also wonder why these aren't hooks), which are new since I was last in this code. I've had no issues disabling this check so far, but heads up, I also don't use floating groups, and looking back over some issues, I broke some things for users thereof back when I fixed this up last time (sorry!---will test in the future).
