### ISSUE TITLE
StumpWM reports "<key> not bound" for bound keys in primary keyboard layout

### ISSUE THREAD

**Issue by MIvanchev** [stumpwm/stumpwm#1136]
My prefix is Ctrl-P. When I set multiple layouts with `setxkbmap -model pc105 -layout us,de,bg -option grp:win_space_toggle` my prefix bindings work only in the initial layout `us`. For other layouts I get errors like "C-P a not bound." which is non sense because the combination is bound in the next layout.

**Comment by MIvanchev** [comment]
More findings, for whatever reason for the non-primary layout, the AltGR key is reported as pressed:

```
key-press: #S(STUMPWM::KEY
  :KEYSYM 112
  :SHIFT NIL
  :CONTROL T
  :META NIL
  :ALT NIL
  :HYPER NIL
  :SUPER NIL
  :ALTGR NIL) 4 *ROOT-MAP*
Awaiting key (*ROOT-MAP* *TILE-GROUP-ROOT-MAP* *GROUP-ROOT-MAP*)
key-press: #S(STUMPWM::KEY
  :KEYSYM 97
  :SHIFT NIL
  :CONTROL NIL
  :META NIL
  :ALT NIL
  :HYPER NIL
  :SUPER NIL
  :ALTGR T) 128 NIL
```

However `xev` reports no such thing.

**Comment by szos** [comment]
Since CLX (the x library stump uses) doesnt natively support altgr we have a somewhat hacky workaround implemented. Ill investigate what may be causing this (I suspect it may be an issue with `parse-key` and `keysym-requires-altgr`, but I'm not sure), but it would be helpful to get some info from you. Specifically: 

1. do you call the function `register-altgr-as-modifier` in your init file?
2. If you switch to a US layout only, what is the output of `(kbd "C-P")`? 
3. Upon switching back to the layout you specified in this report, what is the output of `(kbd "C-P")`?

From an initial 5 minute glance, I think the issue may be premature reporting of a true value from `keysym-requires-altgr`; this function should be strict in its reporting and only return true if the keysym being asked about can be reached via altgr and not reached via a non-altgr key combination. Ill do some more digging to find out.

**Comment by szos** [comment]
Upon further digging and testing, it appears that this is not explicitly an issue with `keysym-requires-altgr`. getting a stump input bar open shows that all key presses are misinterpreted unless in the base keymap. I think the failure is due to the group toggle option causing some kind of change in how information is reported to stump that stump cant handle/parse. Changing the layout to just plain `de`, or even `de,us,bg` doesnt cause any issues. But when adding in the group toggle option everything goes sideways. 

In digging ive found that changing the layout causes the code+state combo sent to stump (logged from `process-input`) to include the altgr modifier (state bit 7). So the issue is with how stump is receiving the key event itself. 

I'll update as i find more, but this may be an issue with CLX and not stump itself. If thats the case we can try to build a workaround.

**Comment by MIvanchev** [comment]
>     1. do you call the function `register-altgr-as-modifier` in your init file?

No 

>     2. If you switch to a US layout only, what is the output of `(kbd "C-P")`?

```
#S(STUMPWM::KEY
   :KEYSYM 80
   :SHIFT NIL
   :CONTROL T
   :META NIL
   :ALT NIL
   :HYPER NIL
   :SUPER NIL
   :ALTGR NIL)
```

>     3. Upon switching back to the layout you specified in this report, what is the output of `(kbd "C-P")`?

```
#S(STUMPWM::KEY
   :KEYSYM 80
   :SHIFT NIL
   :CONTROL T
   :META NIL
   :ALT NIL
   :HYPER NIL
   :SUPER NIL
   :ALTGR NIL)
```

**Comment by MIvanchev** [comment]
> From an initial 5 minute glance, I think the issue may be premature reporting of a true value from keysym-requires-altgr

This was exactly my research result as well. Something seems to be buggy about it.

**Comment by szos** [comment]
I'm actually not sure thats the source of this bug. I do think its buggy, but a refreshing tour through the code reveals that `keysym-requires-altgr` is only called 'on the way down', so to speak; it gets called to find whether a keysym needs the altgr modifier, not to find whether a code+state contains the altgr modifier. 

The actual issue, as far as I can tell, is with using groups. Setting the layout via groups may have the same practical effect as complete keyboard remapping, but because CLX does not implement the XKB extension Stump is unaware of any group changes and thinks it is still using the old layout. 

You can get around this by fully remapping the keyboard using setxkbmap instead of by using XKB groups. Here is an example command that you could bind to `s-space` to get the same/a similar effect: 

```
(defun circularize (list)
  ;; Destructive function!
  (setf (cdr (last list)) list))

(let ((layout (circularize (list 'us 'de 'bg))))
  (defcommand my-layout-swapper () ()
    (setf layout (cdr layout))
    (run-shell-command (format nil "setxkbmap -model pc105 -layout ~A"
                               (string-downcase (string (car layout)))))))
```

**Comment by MIvanchev** [comment]
@szos I was doing a fully remap until now but it's a very suboptimal solution because, for example, with (auto-)grouping, X11 passes ^C as ^C in all layouts. Otherwise it's ^<whatever native character> and little of my mappings continue to function properly. What I could suggest as a workaround is for StumpWM to provide a function I could call myself to make it aware of the layout change. Something like '(update-kb-mappings)'  or something.

**Comment by szos** [comment]
I'm unsure if Stump can be made aware of the layout change - this is ultimately a question of what CLX provides for, which im not intimately familiar with. You could try looking at the mapping-notify event handler (which I'll copy here) as a place to start, but it may be a nonstarter since CLX doesnt support XKB. This event handler is what clears the cache and updates modifier mappings to ensure that the new layout is accounted for. 

```
(define-stump-event-handler :mapping-notify (request start count)
  ;; We could be a bit more intelligent about when to update the
  ;; modifier map, but I don't think it really matters.
  (xlib:mapping-notify *display* request start count)
  (update-modifier-map)
  (sync-keys))
```

**Comment by MIvanchev** [comment]
When is this event handler called?

**Comment by szos** [comment]
The event handler is called whenever the x server sends a mapping-notify event - e.g. whenever the layout is remapped.

**Comment by szos** [comment]
Here is some documentation on the mapping notify event and the way CLX handles events. 

https://tronche.com/gui/x/xlib/events/window-state-change/mapping.html

https://sharplispers.github.io/clx/Events-and-Input.html#Events-and-Input

**Comment by MIvanchev** [comment]
OK, thanks @szos I'll check it out. I hope we can find a workaround for this mess :) It's annoying to change the layout just because ^something doesn't work.

**Comment by dmb2** [comment]
This sounds like an issue with xkeyboard, which clx doesn't support, and subsequently StumpWM cannot respond to.  X11 clients can and do implement xkeyboard responses which is why everything appears to work until you start interacting with stumpwm proper. 

If we can work around it great, otherwise its definitely outside the purview of stumpwm proper.
