### ISSUE TITLE
Help required: ASDF system in standard ASDF load paths (like `/usr/share/common-lib/source`) not considered unless I recompile StumpWM

### ISSUE THREAD

**Issue by MIvanchev** [stumpwm/stumpwm#1191]
Basically the title. If I add a system to the standard path like `/usr/share/common-lib/source` or `~/common-lisp` it's not discoverable from within StumpWM, i.e. `echo "(asdf:load-system \"iterate\")" | stumpish -e eval` unless I recompile StumpWM. Does anyone know how to remedy this situation?

**Comment by dmb2** [comment]
What you need to do is have `asdf:*central-registry*` set to include the path asdf will search in from stumpwm.  You can do this in your stumpwmrc as long as you don't need the package earlier in the init process (I'd be surprised if you did but I have no clue what you're trying to build).  You can check how we handle this in `module.lisp`.  

What I suspect is happening is that your sbcl environment is baking in the a cache of packages when you build stumpwm which is causing things to only get picked up when you recompile.

I see you're piping through stumpish. I, honestly, have never used stumpish beyond a couple times when I was playing around with things.  I start a swank server in my stumpwmrc and connect to stumpwm via slime when I want to hack on it.

You need the following:
```lisp
(require 'swank)
(swank:create-server)
```
Requiring swank can be tricky as its installed with slime in (as of this writing, assuming you're using package.el) `~/.emacs.d/elpa/slime-20240503.1325` 

The problem is that this is a bit of a moving target, when you update slime, the timestamp shifts and that path doesn't work anymore.  Someday I might find a way to dynamically detect this path and load it in stumpwm...

Alternately, it looks like you can just connect and as long as the versions are kinda close you're good to go.

**Comment by MIvanchev** [comment]
I am indeed using swank from stumpwmrc, however I use slimv with neovim and my setup is pretty much constant:

```
(asdf:load-asd (merge-pathnames #p"Develop/slime/swank.asd" (user-homedir-pathname)))
(asdf:load-system "swank")
```

I was just using `stumpish` here to demonstrate the problem. 

>What you need to do is have asdf:*central-registry* set to include the path asdf will search in from stumpwm. 

That's a bit depressing because ASDF docs explicitly discourage the use of `*central-registry*` and also it's a fully surprising element of StumpWM that we should try to address :) Especially because we talk about the standard ASDF locations (described in https://asdf.common-lisp.dev/asdf/Configurations.html) which suddenly stop working (for packages newer than the StumpWM build).

**Comment by MIvanchev** [comment]
OK I checked ASDFs's documentation and found out that ASDF is indeed caching extensively, see https://asdf.common-lisp.dev/asdf.html. To clear the cache once has to call (asdf:clear-source-registry) whenever a  change is made on the file system.
