### ISSUE TITLE
Current-frame will not have a focused window in certain situations

### ISSUE THREAD

**Issue by dbjergaard** [stumpwm/stumpwm#196]
Under certain circumstances switching to a new frame will not focus the window in that frame. Steps to reproduce:
1. From an empty desktop launch two terminals
2. split the screen and place a terminal in each frame
3. close or kill one of the windows
4. switch to the other frame
Expected behavior: other window gets the focus
Observed: the window doesn't have focus and clicking it doesn't give it focus.  The only way to focus the window is to cycle through the frames again.

This behavior is intermittant.  Sometimes the above procedure reproduces the bug, sometimes not.  I'm still looking into what exactly triggers the response.

**Comment by shamazmazum** [comment]
I wanted to send this issue myself and here it is!

Have you tried to eval (screen-focus (current-screen))? It will already have the window you want to give focus to! Is happens after this commit:

https://github.com/stumpwm/stumpwm/commit/1ce4b9a9c12d5e088979b5dd774f3a44642eb5bf

but I don't know what is wrong with it

**Comment by aoterodelaroza** [comment]
Hi David,

I think I know how to reproduce this problem. If, in step 3 (when you
kill the terminal), the pointer is on top of the surviving terminal,
then this issue happens. If the pointer is on the root, then the
behavior is OK.

After a while of back-tracking and (message)s, I think this problem
arises from stale focused windows caused by the handling of some of
Xlib's in-focus events. Specifically, the fifth point in:

https://tronche.com/gui/x/xlib/events/input-focus/normal-and-grabbed.html

(focus from window A to Root or None, and the pointer is in window
P). The last focus-in event is passed to the handler with window
P. Hence, the old window remains focused even if it's not there
anymore.

This problem also arises in other cases, although stumpwm's behavior
is not weird, so maybe that's why it's gone unnoticed. For instance,
1) create a single terminal in a group, 2) gnext to the next empty
group, and 3) message current-screen's focus to the output. You'll see
that the window from the previous group is still focused for
stumpwm. If you gnext again and the new group is empty, then the focus
becomes nil, as it should.

A quick-and-dirty solution is to pass the kind to the focus-in event
handler, and then only focus if the kind is not equal to pointer. This
works for me, and skimming through the other cases with kind = pointer
in the documentation it seems a reasonable thing to do. However, I'm
not entirely certain it won't create additional bugs because I've just
started reading the Xlib/clx documentation and my LISP is shaky at
best.
