### ISSUE TITLE
StumpWM crashes on startx

### ISSUE THREAD

**Issue by lehitoskin** [stumpwm/stumpwm#203]
I installed StumpWM and found that when I tried to login with the XSession, the screen went blank save for the mouse. Upon further investigation, I found out that StumpWM is crashing when I call it. I have also tried installing from git source, but it gives the same result.

Here is the error:
```common-lisp
debugger invoked on a SB-INT:SIMPLE-PARSE-ERROR in thread
#<THREAD "main thread" RUNNING {10044BE363}>:
  no non-whitespace characters in string "".

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

(no restarts: If you didn't do this on purpose, please report it as a bug.)

(PARSE-INTEGER "" :START 0 :END NIL :RADIX 10 :JUNK-ALLOWED NIL)
```

This is all brand new so I have nothing in .stumpwmrc. I also tried looking at .xsession-errors and Xorg logs, but they say nothing at all about StumpWM.

I'm running Gentoo and I emerged StumpWM version 0.9.9 with SBCL version 1.2.11

**Comment by dbjergaard** [comment]
as a intermediate solution, can you try runnin 0.9.8?  If you have any experience with git, you could try rolling back each commit until you get a working build.  

The stack trace doesn't give any hint of where in the code this issue is happening.  Do you have access to the "copy-unhandled-error" function?

**Comment by lehitoskin** [comment]
I've tried 0.9.8 and many different commits, but they all give the same error as before. Also, I don't seem to have access to "copy-unhandled-error" since when I run stumpwm it immediately gives that error.

...Testing this in a Gentoo VM is producing an identical error. Also, I found this rather interesting tidbit after emerging StumpWM from Portage:

```
 * QA Notice: The following files contain writable and executable sections
 *  Files with such sections will not work properly (or at all!) on some
 *  architectures/operating systems.  A bug should be filed at
 *  http://bugs.gentoo.org/ to make sure the issue is fixed.
 *  For more information, see http://hardened.gentoo.org/gnu-stack.xml
 *  Please include the following list of files in your report:
 *  Note: Bugs should be filed for the respective maintainers
 *  of the package in question and not hardened@g.o.
 * RWX --- --- usr/bin/stumpwm
```

This seems relevant, but I don't really understand what it means.

**Comment by dbjergaard** [comment]
After re-reading your QA notice, I think this is warning you that the image made can modify itself when it runs (ie it loads your stumpwmrc which can reprogram/redefine parts of the program). This is can be viewed as a security issue, and the warning is that the binary may not work on systems that disallow this sort of thing.  Of course that's my reading, not necessarily the truth.

As for your bug,  the problem is that something is returning an empty string to parse integer.  Given that you have an empty stumpwmrc and you say the issue affects you in 0.9.8, I'm inclined to think the issue is in primitives.lisp, stumpwm.lisp or head.lisp.  Is there any more of the stack trace? You mentioned trying this in a VM, have you tried it in another distro?

**Comment by lehitoskin** [comment]
There's nothing more in the error message I got on Gentoo, but after thinking I tried compiling it on an Ubuntu VM:

StumpWM version 0.9.9 compiles (and properly runs) against SBCL version 1.2.4 (the version available from APT), but fails to compile in version 1.2.11 and version 1.2.12.

Hmm. Maybe I'll try using that version in Gentoo.

**Comment by dbjergaard** [comment]
Strange that this works in ubuntu but not gentoo.  I don't know enough about the latter to suggest any good debugging strategies.  Do you get the "Welcome to StumpWM" banner in the upper right corner of the screen? If not, then I suspect that the error may be happening when it tries to render that string but can't because one of the color strings is blank... Just a working theory, but that doesn't explain why its an OS specific bug...

**Comment by lehitoskin** [comment]
I only get that banner in Ubuntu. In Gentoo there's just a black screen and none of the keyboard inputs do anything.

**Comment by PuercoPop** [comment]
We could change hex-to-xlib-color to be ensure the length of the color string before trying to access by index.

```lisp
(defun hex-to-xlib-color (color)
  (cond
   ((= 4 (length color))
    (let ((red (/ (parse-integer (subseq color 1 2) :radix 16) 255.0))
          (green (/ (parse-integer (subseq color 2 3) :radix 16) 255.0))
          (blue (/ (parse-integer (subseq color 3 4) :radix 16) 255.0)))
      (xlib:make-color :red (+ red (* 16 red))
                       :green (+ green (* 16 green))
                       :blue (+ blue (* 16 blue)))))
   ((= 7 (length color))
    (let ((red (/ (parse-integer (subseq color 1 3) :radix 16) 255.0))
          (green (/ (parse-integer (subseq color 3 5) :radix 16) 255.0))
          (blue (/ (parse-integer (subseq color 5 7) :radix 16) 255.0)))
      (xlib:make-color :red red :green green :blue blue)))))
```

We could also leave a t case that does the latter conversion and warning; or throw an error on with an informative message.

**Comment by dbjergaard** [comment]
looks good, PR welcome! If not I can merge it when I get time...

**Comment by PuercoPop** [comment]
Will do

**Comment by PuercoPop** [comment]
I've added the change as part of #211 fyi

**Comment by dbjergaard** [comment]
Ok thanks! I'll close this issue when we get the other PR merged.
