### ISSUE TITLE
Search in windowlist only searches displayed titles, not full titles

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#220]
So if the application's name is hidden because the title is too long, searching for it won't work.

My current solution is to change the `*window-format*`, but then it's not shown as I'd like it to be... but as I need it to be searchable.

I guess the code to fix is around [here](https://github.com/stumpwm/stumpwm/blob/0303086e94cebd22614d06a640767b21a294cd4e/menu.lisp#L206-L237), but I couldn't make sense of it.

**Comment by jorams** [comment]
The cropping of the name happens because [`SELECT-WINDOW-FROM-MENU`](https://github.com/stumpwm/stumpwm/blob/0303086e94cebd22614d06a640767b21a294cd4e/window.lisp#L951) passes the windows through a format, which defaults to `*window-format*` (in [`WINDOWLIST`](https://github.com/stumpwm/stumpwm/blob/4b6146dd8297ece3bc07127bd2bd593e41d2faeb/window.lisp#L1065)).

You could define an alternative command that uses a different format that doesn't crop titles. The searching code ([`CHECK-MENU-COMPLETE`](https://github.com/stumpwm/stumpwm/blob/0303086e94cebd22614d06a640767b21a294cd4e/menu.lisp#L150), called by `SELECT-FROM-MENU`, which you linked to) never sees the full title of the command, because the menu never sees it.

**Comment by ralt** [comment]
> The searching code (CHECK-MENU-COMPLETE, called by SELECT-FROM-MENU, which you linked to) never sees the full title of the command, because the menu never sees it.

Indeed, that's the observed behavior, and I think this is a bug. Isn't it?

**Comment by dbjergaard** [comment]
HI @jorams @ralt, can you check if the PR #241 looks good? I'll merge it if I don't hear that anything needs changing.

**Comment by ralt** [comment]
I haven't tested it yet, but I already love it. I'll try to take some time this weekend to try it out.
