### ISSUE TITLE
Strange colours in windowlist after commit c01fba3

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#253]
After commit c01fba3, the selected line in `windowslist` has strange colours.  Only the background colour is inverted and the text colours remain the same.

Before: 
![before](https://cloud.githubusercontent.com/assets/6874951/15094126/35173192-1471-11e6-9446-e8a0f6d69e97.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/6874951/15094131/3c54bdbc-1471-11e6-9b30-a0e87027023c.jpg)

**Comment by NicolasPetton** [comment]
I'm using ttf-fonts, but I don't have this issue.

**Comment by Jehops** [comment]
Can you try a simple `~/.stumpwmrc` with this one line?
`(setf *window-format* "^[^7*%n^]^[^6*%s^]%256t")`

**Comment by dbjergaard** [comment]
If the default *window-format* works (I haven't tweaked mine and it works) the issue may be in the format parser.  Since the ttf-fonts fix was to remove an apparently redundant invert-rect call, I'm inclined to try to fix the parser rather than reverting the fix for the ttf-fonts bug.

**Comment by Jehops** [comment]
I haven't looked at the code, but, superficially, it seems the format parser is misinterpreting the `*` in, e.g., `^6*`. 

P.S. The before image has messed up contrast.  It actually looks as it should.  I just couldn't take a proper screenshot when the window list was showing.

**Comment by dbjergaard** [comment]
can you try using shutter? I've attached what mine looks like.  You just need to add a delay to when the screenshot fires. (I think scrot will do this as well)
![window_list](https://cloud.githubusercontent.com/assets/171410/15262696/f534d1c2-1931-11e6-8bf3-fbacc8c1b95e.png)

**Comment by Jehops** [comment]
Before:
![before](https://cloud.githubusercontent.com/assets/6874951/15264947/516c1054-1950-11e6-9f7d-22e8c35256d1.png)

After:
![after](https://cloud.githubusercontent.com/assets/6874951/15264949/61662ef4-1950-11e6-9661-c9f96b5661c3.png)

**Comment by jorams** [comment]
I've just pushed cb0f1935bfb4a728dc02a90a58608ece52c003d4, which improves how this is handled. Because we no longer truly invert the entire rectangle, not all colors are inverted, but we can at least handle the default foreground and background properly.

Before:
![before](https://cloud.githubusercontent.com/assets/516174/18802788/630a3670-81eb-11e6-84d3-6173fac4a649.png)

After:
![after](https://cloud.githubusercontent.com/assets/516174/18802793/69c4550e-81eb-11e6-8afd-0c691dd2cd71.png)

I'm closing this. If you don't consider this a satisfactory solution, feel free to reopen.
