### ISSUE TITLE
Add interactive command macro

### ISSUE THREAD

**Issue by caioaao** [stumpwm/stumpwm#292]
Implemented it to navigate between frames without having to type the prefix again (eg.: to move focus to two frames to the left, I have to type `C-q o l l` instead of `C-q l C-q l`), just like `resize` does.

My implementation is [here](https://github.com/caioaao/stumpwm.d/tree/master/modules/icommand), but I'd like some input if it's worth integrating it with stumpwm's project or just leave it as a standalone module (also I'm very new to CL, so I wouldn't know how to do any of the two options properly).

**Comment by dbjergaard** [comment]
I think this is an important abstraction, and I'm interesting in putting it in stumpwm proper.  Here's what I would want in PR to merge:
1. This goes in its own file in `stumpwm/icommand.lisp` 
2. You can merge the file into stumpwm instead of having its own package, just modify stumpwm.asd as necessary
3. Restructure iresize to use your new macro instead of the current code
4. Update the manual to include documentation describing icommand and pointing to iresize as an example of how users can implement the macro in practice

I know this seems like a tall order, but I can see the power of what you've implemented and I want to make sure it is properly exposed to everyone who uses stumpwm.
We can clean up any non-lispy idioms in the code review of the PR.

**Comment by caioaao** [comment]
Sorry for the long delay, I've been too busy during December. I'll try doing it during next weeks. I still have to figure how to bootstrap and share state between commands when an interactive command "session" starts, but I think I have a simple solution to that.

**Comment by caioaao** [comment]
What I've done so far: https://github.com/stumpwm/stumpwm/commit/9615e3d84b4390f647e0897ba1bddb611a7d1235

Dos are still missing, but you can see how this works on the new `iresize` implementation.

**Comment by dbjergaard** [comment]
I'm going to close this since the PR is now open and being reviewed.
