### ISSUE TITLE
Remove unnecessary use of multimethods

### ISSUE THREAD

**Issue by dmh43** [stumpwm/stumpwm#300]
There are a few methods that I believe make more sense as functions rather than as multimethods. For example `group-add-window` and `focus-window`. I'd like to go through and convert these to functions. What are your thoughts on this?

**Comment by PuercoPop** [comment]
Why do you think they are unnecessary? Performance? Normally generic functions are used for extensibility. I can't see why we would need to customize FOCUS-WINDOW on a per kind of window basis (maybe a hook, but that wouldn't need a generic function so I I'm not against turning FOCUS-WINDOW into a function (although I haven't checked for uses in StumpWM-contrib yet so I may be mistaken). 

In the case of GROUP-WINDOW-ADD I don't see why we would want the loss of extensibility for, we even make use of that extensibility inside of StumpWM itself. I've read in #298 that is because you don't know how to avoid duplicatating code. Maybe renaming the current WINDOW Class to STANDARD-WINDOW and having the WINDOW class to be an abstract base for class would allow you to define a method specializing on the base window with the common code and using (call-next-method) in the more specific method? (I haven't been able to review the code properly as I am currently on my phone so take what I'm saying with a pinch of salt)

**Comment by jorams** [comment]
`GROUP-ADD-WINDOW` is part of the group protocol, which was designed to support different kinds of groups with different kinds of behaviours. It should definitely stay a generic function, but the group class hierarchy might need some work to make the problem you're working on easier.

This is probably also a consequence of the fact that you're essentially merging the floating group's functionality into the tiling group, while keeping a separate floating group alive. It's part of why I suggested merging the two groups in their entirety.

`FOCUS-WINDOW` is similarly part of the window protocol, but I see less of a point in that protocol. Much of the functions there depend heavily on the group the window is in. Re-structuring it could be a good idea.

**Comment by dmh43** [comment]
Thanks for the feedback @PuercoPop and @jorams, that clears things up quite a bit. Let's stick with the generic functions.
