### ISSUE TITLE
Reorganize code into more meaningful namespaces

### ISSUE THREAD

**Issue by dmh43** [stumpwm/stumpwm#301]
Currently, the only packages in the project are the main `stumpwm` package and the `stumpwm.floating-group` package. I'd like to merge the `floating-group` namespace into the `stumpwm` namespace as well as create new namespaces to group together related code to make the code more modular.

**Comment by jorams** [comment]
The split of the floating group into its own package was the start of an effort to reorganize into more meaningful namespaces. It is a relatively standalone part of the codebase. Sadly, my efforts towards further reorganization stranded due to the massive lack of structure.

I've since started again a couple of times, most recently by splitting off and refactoring the UI code. That's what I'm working on in #289.

I think better organization is definitely welcome.

**Comment by dmh43** [comment]
I see! I'll keep an eye on the progress of that branch and try to minimize conflicts

**Comment by dbjergaard** [comment]
@dmh43 Thanks for all the recent activity/contributions!  Since you, @jorams and @PuercoPop are fairly active, we should probably have an email chain to discuss development plans.  (I know IRC can be better sometimes, but I'm available at very inconsistent times so email works better for me)

You can read the discussion of #289 to get an idea of how I want to move the development forward.  There is one bug standing in the way of a 1.0.0 release.  When that one is fixed (see the issue tracker) I will release 1.0.0 as the final version of stumpwm using the old policies of package management organization and dependencies.  Moving forward I want to restructure things as @jorams has suggested.  I also want to increase the dependencies and decrease the code we have to maintain.  I also want meaningful unit tests that allow us to make changes to the codebase with the confidence that we won't break everyone's experience.  I also want to move to support sbcl only and remove all the legacy code for flavors of lisp that aren't used anymore. 

Thanks again for your contributions.  I'm excited to see more!

**Comment by dmh43** [comment]
Exciting! Generally, email is also more manageable than IRC for me.

**Comment by PuercoPop** [comment]
Email works better than IRC in this case, especially when the IRC channel is not logged. I've been meaning to reply to your RFC regarding dependencies in StumpWM, sorry that I've procrastinated so long.

**Comment by dbjergaard** [comment]
Please move discussion to the project I just created. Or StumpWM devel depending on your taste.

**Comment by PuercoPop** [comment]
@dbjergaard I like the idea of using projects to loosely co-ordinate efforts more effectively. But I'm not very familiar with the feature yet. How are we suppose to discuss things there?

**Comment by dbjergaard** [comment]
I naively assumed we could have comments running on each little sub-goal.  I haven't used the feature either.  Lets use the mailing list for discussion and the project for concrete goals.  I like to keep the issue tracker for issues/bugs rather than meta-goals.  The current meta-issues were made long before the projects feature was added.

**Comment by PuercoPop** [comment]
@dbjergaard ok. One thing we can use projects for is to keep track of feature requests as well
