### ISSUE TITLE
STRING-TO-BYTES doesn't specify encoding

### ISSUE THREAD

**Issue by PuercoPop** [stumpwm/stumpwm#320]
Which is problematic as`sb-impl::*default-external-format*` is not guaranteed to be utf-8 so we it can't know how it will be serialized . We also provide a string-to-bytes-utf-8 function. Should we delete string-to-bytes and replace it with string-to-utf-8?

Also BYTES-TO-STRING could be repalced with `(utf8-to-string (vector data))`

**Comment by jorams** [comment]
`STRING-TO-BYTES` and `BYTES-TO-STRING` are only used by `handle-stumpwm-commands`. It receives data from a window property and sets data in another window property. The one use of this I know of (and can find) is in Stumpish, where it will use the encoding set in the environment. It appears these functions try to do that as well, so I'm not sure if we can just throw them away.

**Comment by dbjergaard** [comment]
I'm not seeing string-to-bytes in the codebase.  As far as stumpwm is concerned, the string-to-bytes and the converse would be the conversion from a byte (0-255) to a byte string (an array of bytes). 

Eventually we'll want to handle data<->string conversion using the sbcl utf8 conversions, but for now I'm closing this since the symbol isn't present in the codebase.  Feel free to reopen if I'm mistaken.
