### ISSUE TITLE
"There is no package named SB-EXT" on Clozure CL

### ISSUE THREAD

**Issue by duncan-bayne** [stumpwm/stumpwm#342]
When compiling from HEAD:

```
/usr/local/bin/ccl --load ./make-image.lisp
Read error between positions 1294 and 1534 in /usr/home/duncan/stumpwm-install/wrappers.lisp.
> Error: There is no package named "SB-EXT" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
```

Looks like there's an invocation of something inside `SB-EXT` that should be, but isn't, conditional upon SBCL being used?

System details:

```
$ ccl --version
Version 1.11  (FreebsdX8664)
$ uname -a
FreeBSD x220 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by PuercoPop** [comment]
No, After 1.0.0 we dropped support for all implementations but SBCL

**Comment by duncan-bayne** [comment]
Wow!   I hadn't guessed that, from the presence of all the implementation-conditional stuff in `wrapper.lisp`.

Well - thanks for StumpWM, it's been a blast.  But I've recently switched to FreeBSD, and SBCL there is a) without a maintainer, and b) without threading.  So I think I'll try a different window manager for now. 

Are there plans to support implementations in the future?  Are there particular blockers on other implementations that I could look at addressing?

**Comment by PuercoPop** [comment]
@duncan-bayne you can still use the 1.0.0 version, which we'll continue to support. Too bad to hear that is the state of SBCL on FreeBSD

**Comment by dbjergaard** [comment]
@duncan-bayne I'm a little confused since one of the reasons I chose to support sbcl only was its improved support for multiple platforms and architectures.  They're website lists that FreeBSD is supported: 
http://sbcl.org/platform-table.html

If SBCL doesn't have a entry in whatever the BSD's package manager is that's another thing entirely.  It might not make it easy to use SBCL, but it should be technically feasible.

As for threading: If this is a deal breaking feature there isn't much we can do.  I'm not sure what a multi-threaded window manager looks like.  I can see places where it would be nice to be able to have threads doing different things, but for the core window management, I don't see how multiple threads makes life better.

**Comment by fstamour** [comment]
I don't know a lot about FreeBSD, but it seems there is a maintainer for sbcl since January:  https://svnweb.freebsd.org/ports/head/lang/sbcl/pkg-plist?view=log
