### ISSUE TITLE
crash when using *message-hook*

### ISSUE THREAD

**Issue by dmb2** [stumpwm/stumpwm#343]
Reported on stumpwm-devel 

I just rebuilt against GitHub@head and still reproduce a reliable
        crash -- this crash started happening about mid-February 

 Basically Stumpwm crashes if I do something like this:  [12:18]
```lisp
 (setq *message-hook* (list #'(lambda nil (echo "foo"))))
```
 I reduced the crash to the above minimal example: in my  actual use
        case, I used to have a function on that hook that spoke the message to
        .  [12:19]

 incidentally, the same configuration is working fine on my desktop
        running Trusty  -- but a 3.x kernel 

 Looks like the above crashes all of X  [12:20]
```
 fatal error encountered in SBCL pid 2614(tid 140737353893696):  [12:21]

 %PRIMITIVE HALT called; the party is over.
 Error opening /dev/tty: No such device or address
 (obno-popup-notifier:2534): Gdk-WARNING **: obno-popup-notifier: Fatal
        IO error 11 (Resource temporarily unavailable) on X server :0.
 xterm: fatal IO error 11 (Resource temporarily unavailable) or
        KillClient on X server ":0"
g_dbus_connection_real_closed: Remote peer vanished with error:
        Underlying GIOStream returned 0 bytes on an async read
        (g-io-error-quark, 0). Exiting.
```
 12:20:44 raman-glaptop2 ~ $ 
```
 stumpwm version from stumpish: >
 1.0.0-88-g7d63123 Compiled On Sun Apr
        02 2017 10:53:41  [12:23]
```
 is there somewhere I should email the above?

**Comment by dbjergaard** [comment]
The next step in narrowing this down is to use git to track down the commit that
caused the break.  Failing that, two things stick out to me as odd:
1. the "Error opening /dev/tty" is strange, I can't find anywhere in the
   backtrace for "echo" that needs a pseuod-terminal
2. The obno-popup-notifier is unfamiliar to me, I haven't seen those types of
   errors before. Did Ubuntu recently change the notification handler?

Next steps:
Is it possible to get a backtrace when the crash happens? 
If not, please set up the debugging output to a file and see what is in the log
when the crash happens.

Revert the commits until you find a version of stumpwm that doesn't crash using
your recipe.

**Comment by jorams** [comment]
I think the problem might just be that StumpWM totally crashes. The minimal testcase puts a function in `*message-hook*` that doesn't accept any arguments, while the hook is called with any number of arguments. That'll cause StumpWM to crash (it should catch the exception, but it might not handle everything properly in every case), causing the X server to shut down, causing other programs to fail when talking to X.

**Comment by dbjergaard** [comment]
I looked at this, and I can't get a working example of how to use message hook properly. Everything crashes due to some infinite recursion.  Sometimes sbcl catches it, sometimes not, all the time stumpwm locks up until it either crashes or is killed

**Comment by dbjergaard** [comment]
@jorams can you look at `run-hook-with-args` in primitives.lisp? I'm specifically curious if you see any chance for the macro to cause infinite recursion because of the way its structured.  There's a with-simple-restart sandwiched in the with-restarts-menu that might be causing the issue.

**Comment by mtlll** [comment]
I've looked into this a bit and I think I've figured out what's causing it.

The issue is not run-hook-with-args per se. The infinite loop stems from the fact that when an error occurs in invoking *message-hook*, Restarts-menu is called, which ultimately ends up invoking *message-hook* again, and the error repeats.

This can be confirmed fairly easily by wrapping the body of RESTARTS-MENU in (let ((*message-hook* nil)) ...)

This makes the problem go away. But clearly isn't an ideal solution. From a quick glance it would appear that errors in *menu-selection-hook* would cause the same problem as well.

I'm not exactly sure what the best way is to handle this issue in the most general way possible. I've made some attempts at working around this using let bindings to stop RESTARTS-MENU from being invoked further down the call stack from itself, but it doesn't work. Even if it avoids RESTARTS-MENU and signals the error further up, that triggers it anyway when stumpwm wants to simply print the error as a message.

One possibility might be to define a condition type for this situation and handle that as far up the call chain as possible, printing it without invoking any hooks. Either way it might be a good idea to make a move to disable hooks in certain error handling code paths. It wouldn't surprise me if there's other edge cases where this race condition happens.

I'd appreciate it if you'd assign me to this issue. I intend to continue investigating it.
