### ISSUE TITLE
Input-field on wrong head when no window in selected frame

### ISSUE THREAD

**Issue by impaktor** [stumpwm/stumpwm#365]
I have two heads, (laptop + external monitor), typically, if I have a group with no windows on the external monitor, selecting that frame and `C-t M-; mode-line` opens the input field for "mode-line" on the wrong head (i.e. laptop monitor), and as a result, rather than toggle the mode-line ON for external monitor, it turns it OFF for the laptop-monitor.

This can be circumvented by first opening a window in the selected frame on the external monitor, before C-t M-;

Interesting, the dashed frame around the empty frame, gets a black input window "dent", but the content is actually on the other head.

**Comment by jorams** [comment]
Thanks for opening this :)

Fixed in 058dafe5474632ff746e358854bd580bef6784d6.

**Comment by impaktor** [comment]
Thanks! Fixed it, but I think I might see a remnant of it. So with:

```
(defcommand dmenu () ()
            "Make dmenu use color from theme variables"
            (run-shell-command (cat "dmenu_run -nf " FOREGROUND-COLOR
                                    " -nb " BACKGROUND-COLOR
                                    " -sb " SELECT-BG-COLOR
                                    " -sf " SELECT-FG-COLOR
                                    " -fn \""FONT"\"")))
```

and then `C-t M-; dmenu` from an empty frame on second head, I get the menu on the other / first head. Not sure if it's related.

**Comment by jorams** [comment]
That's mostly handled by dmenu itself. It looks for a focused window and places itself on the head it overlaps the most. If there is no focused window, it uses the head the pointer is on. But that doesn't work, because StumpWM always keeps a window in focus. The fallback focus window is at `0,0`, so dmenu will place itself on that head.

I wonder if it's a good idea to move the focus window around based on pointer movement... 🤔
