### ISSUE TITLE
How to define your own modal keybindings?

### ISSUE THREAD

**Issue by vyp** [stumpwm/stumpwm#375]
I.e. like in `command-mode` where you don't have to press the prefix key. But instead of just having that, I'd like to be able to define my own set of keybindings where you don't have to keep pressing the prefix keybinding each time, i.e. it stays in that "mode" until you exit out of it (say with escape). Like how @caioaao describes in #292:

> [...] without having to type the prefix again [...]

`iresize` does this so I think you can just use `define-interactive-keymap`? I'm new to lisp so I'm not exactly sure how to use it, which is why I'm asking since there doesn't seem to be any other documentation about it apart from the docstring.

I want to be able to define a keybinding on the top map that enters a 'window movement' mode where I can just keep pressing h/j/k/l to move a window around, until I abort with escape.

**Comment by caioaao** [comment]
I actually have something like that, but to move focus. You can see it [here](https://github.com/caioaao/stumpwm.d/blob/f9c75be0c5db4b431d33f557a40451a943a35590/keymaps.lisp#L21)

**Comment by caioaao** [comment]
@yip: that's weird. I copied your code and it worked fine here (I actually included that in my config: https://github.com/caioaao/stumpwm.d/commit/818f733a4bbc6d7b78b9678869d05a4a065a5c2f). idk what could be wrong here.

@dbjergaard About the modal mode, I think it could be a good idea, but idk if it should be a default config (I know I like to pick which commands I want an interactive mode for). looks like emacs vs spacemacs :). What I'd like to see is a composition of `iresize`, `imove-focus` and `imove-window` into an interactive window manipulation mode, but again: the default config probably won't please the majority and the majority would have to write their own interactive modes as they please.

About not removing the default stumpwm keybindings: I did that way because `iresize` was really confusing to me. We're in a mode for resizing windows and all of the sudden we can also move them, write __parts__ of texts in the buffer in focus... I think it also caused some weird issues when moving between workspaces.

I really like @vyp 's suggestion about showing the mode on the mode-line, but idk how that'd work. does stumpwm have something like major/minor modes?

**Comment by vyp** [comment]
@caioaao Ahh ok. I've also been having problems with using `load-module`, some error about not being able to create directory `/build/`. So I assume it's just something to do with my system. :disappointed: I wish there were detailed logs/traces somewhere for these errors though.

@caioaao What would be the difference between a major and minor mode? E.g. in emacs the major mode is usually the type of buffer, but how would that transfer to a wm, or do you mean something else? Not opposed to it, just seems a bit overkill from what I understand atm.

Anyway in that case my original question has been answered, so I'm happy to close this issue. Feel free to reopen though if anyone wants to!

**Comment by caioaao** [comment]
@vyp it'd be a loose inspiration from emacs's major/minor modes. here, major modes would set stumpwm's default behavior, while minor modes only change it. it would have to be something group-wise probably. anyway, just thinking out loud :)

**Comment by vyp** [comment]
That makes more sense! I think it might be a good idea if there's interest in it.

**Comment by vyp** [comment]
Btw, this feature is basically just like [hydra](https://github.com/abo-abo/hydra) emacs package. :+1:

**Comment by idosilverwater** [comment]
@vyp I too am facing this problem (the variable is unbound). And I don't fully understand your solution.
when you said you used `load` as a work around, what exactly did you load?

**Comment by vyp** [comment]
Wow I used to type a lot.

@idosilverwater Unfortunately I didn't solve `imove-window` being unbound. I just meant I was using `load` instead of `load-module` to load other unrelated lisp files like [here](https://github.com/vyp/dots/blob/03645faa9d3527b406e668eed34aeafafe90f664/stumpwm/.stumpwm.d/init.lisp#L7). And that the non-working `load-module` probably meant something was wrong with my installation.

I don't think I ever figured out what was wrong, probably a lack of time to do so more than anything. So I don't use stumpwm anymore, sorry I can't help further.
