### ISSUE TITLE
If SBCL_HOME is unset on the build, calls to require will fail

### ISSUE THREAD

**Issue by ahungry** [stumpwm/stumpwm#388]
I implemented a small update to the build to fix this:

https://github.com/stumpwm/stumpwm/pull/387

A lot of online references mention a call to `(require 'swank)` to start the swank server - unfortunately, under some OS systems, SBCL_HOME will not be set (causing it to default to NIL and calls to require to complain about no true pathname for NIL/).

This will at least warn the user the are missing the setting in their ENV, if sbcl is chosen as the lisp implementation.

**Comment by jorams** [comment]
Recent versions of SBCL (since 1.3.15, so we're talking about 6 months here) don't require `SBCL_HOME` to be set. They will use a default (sbcl build-time) value if it is not in the environment. Therefore, this warning would be unnecessary. Maybe we could check to see if the SBCL version is older than 1.3.15?

`make-image.lisp` is already set up in such a way that, if `SBCL_HOME` is not set when dumping the image, it will also not be set in the runtime environment.

**Comment by dbjergaard** [comment]
I like keeping the warning for now, when 1.3.15 gets down to debian stable we can remove it.
