### ISSUE TITLE
Can't set any font

### ISSUE THREAD

**Issue by schvabodka-man** [stumpwm/stumpwm#405]
Hello there. The trouble is simple - i just can't set the font in stumpwm. When i do use xft to compose font i get %fontname% not found(but this fonts are on my machine), when i simply write string "by hand" just nothing happens. I've tryed a little bit in lisp repl and by far i got that even after (clx-truetype:cache-fonts)
after running (clx-truetype:get-font-families) i'm simply getting NIL(and cache-fonts actually returns hash tabl with 0 entries). Value *font-dirs* set properly ("usr/share/fonts" and stuff). So that's probably releated to font caching? Are these any solutions to these problem?

**Comment by dbjergaard** [comment]
If you are using clx-truetype you will have to populate the cache once, and then list the fonts. The name you use will depend on the names extracted by clx-truetype. 

If you do not use clx-truetype you can only use fonts available from xfontsel.  This is a limitation in the way clx renders fonts.

I have an experimental library that allows you to use opentype (otf) and truetype (ttf) fonts. It follows the same interface ans clx-truetype:
```
(set-font (make-instance 'clx-ft2:font :family "Input Mono"))
```
Otherwise you would do:
```
(set-font "-lispm-fixed-medium-r-normal-*-13-*-*-*-*-*-*-*")
```
where the string is the one from xfontsel.

My experimental library works, but its buggy so stick with clx-truetype.  You'll only be able to load ttf files.
