### ISSUE TITLE
Rename window

### ISSUE THREAD

**Issue by ralt** [stumpwm/stumpwm#417]
Hi,

Is it possible to rename a window? Sometimes when I have 10 open terminals, it gets tedious to find the one I want to work on.

Cheers

**Comment by PuercoPop** [comment]
@ralt I think [`window-user-title`](https://github.com/stumpwm/stumpwm/blob/master/window.lisp#L61) is what you are looking for. When deciding the window name to display [`window-name`](https://github.com/stumpwm/stumpwm/blob/master/window.lisp#L239) looks at it first.

**Comment by ralt** [comment]
Oh, that looks great, thanks! I'll try to cook up a command to rename the active window.

**Comment by jorams** [comment]
That command already exists: [`title`](https://github.com/stumpwm/stumpwm/blob/master/window.lisp#L1000).

**Comment by ralt** [comment]
Oh my, that's perfect.

Thanks!

**Comment by jgarte** [comment]
@PuercoPop 

Hi, When I rename a window I notice that the name is lost about minute later. 

In other words it's not found in `pull-from-windowlist`.

Do you happen to know why?

**Comment by PuercoPop** [comment]
>  name is lost about minute later.

Most likely it is because the window title by the application it self. The window title can be set by setting the `_NET_WM_NAME` prop of a window. You can check this value by using `xprop _NET_WM_NAME` and clicking on the window of interest. For example Firefox changes the window title to match the title of the page of the current tab.

Although pull-from-windowlist uses more than just the title to present windows.
