### ISSUE TITLE
How can we best support this amazing project?

### ISSUE THREAD

**Issue by ckuttruff** [stumpwm/stumpwm#463]
This has been everything I've waited for in a windows manager.  I just got things up and running on FreeBSD and I couldn't be more thrilled.  Can we donate somewhere?  I didn't see a link for that

If there's any other way to support, please let me know, cause I can't tell you how much I appreciate this project.  I should have gone to sleep long ago, but but I'm running on far too much pure, borderless, clutter-free, snappy window awesomeness adrenaline right now.

THANK YOU so much for your work on this project.
A+; 100%; Computing at its best

**Comment by dbjergaard** [comment]
Welcome! 

I hope you'll become an important part of our community.  We (as a project) used to accept donations, but since I've taken over we haven't.  In my opinion it brings up a bunch of hairy issues I don't want to deal with (who should receive the money, how should it be spent, etc).  

Our author list is long with contributors and we have a few people who donate their time reviewing code and helping ensure pull requests are of the highest quality.

If you have any time to contribute to the project there are plenty of places we can use man-hours:
- Documentation :: proofreading the manual, documenting portions you find confusing, writing tutorials/blog posts
- Videos :: We could really use a series of youtube videos for people that prefer to learn that way. They could be as simple or as complex as needed and cover any topics stumpwm related
- Contrib Modules :: Many of our contrib modules have zero documentation.  This would require learning what they were intended for and documenting it which would require some lisp skills, but very little.

If you are short on time but want to contribute something tangible, I am going to start implementing the xkeyboard extension in clx and I could really benefit from a non-US keyboard to test with.  I can make do with a non-us layout, but sometimes having the device is the best.

If you are short on time and capital, just be a good member of the community.  Check our bug reports and try to reproduce them. If you can document them in grave detail.  Subscribe to stumpwm-devel and get involved with discussions there, ask questions, help other new users and lurk on irc.

Once again, welcome! And please enjoy your stay.

**Comment by ckuttruff** [comment]
@dbjergaard thanks so much for your detailed reply.  I think documentation and videos would definitely be a good fit.  I'm still getting used to the basics but I'll take notes and start making tutorial vids cause I actually like learning that way sometimes too.

And documenting contrib modules soumds great cause some of those additions sound awesome and like things I'll be using.  Mostly been writing clojure nowadays, but def have some CL bg and hope to be able hack on some basic stuff as I get more familiar.

Thanks for all your work and the thorough response.  Gonna be diving into dics, modules, extensions, etc tonight.  Will try for a screencast once I'm not fumbling with frames and smashing windows  :)

The truly extensible window manager!
Psyched!!

Really, it's so beautifully simple and powerful 
:raised_hands: :beers: :computer: :smile:
