### ISSUE TITLE
C-t ! tab completion freezes everything at first

### ISSUE THREAD

**Issue by jbaber** [stumpwm/stumpwm#471]
The first time I `C-t ! ter<tab>` everything freezes while some kind of one-time work is done. Thereafter, tab completion works fine.

**Comment by sdilts** [comment]
After looking into this, it seems like this is partially out of our control. The delay is caused by building the cache of available programs, which occurs almost instantly in a session that has already computed the cache at least once. To see for yourself, delete the cache:

    (setf *path-cache* nil)

Try to complete something again by using `C-t !` again, or by using the function that actually computes the completions:

    (complete-program "ter")

There is no noticeable delay after doing this more than once. The same thing occurs with other programs such as `dmenu`; the first time it is ran, it is much slower than the subsequent calls. Plus, when `dmenu` is ran before the first call to `complete-program`, delay is seen in `dmenu`, but not in `complete-program`.  Furthermore, this delay can occur again if the cache needs to be rebuilt after it hasn't been rebuilt in some time.

This leads me to believe that the delay is caused by the OS needing to do some work, and not by stumpwm itself. There's nothing obviously wrong with the algorithms involved in this process either; they start at line 108 in `user.lisp` if you want to take a look at them.

**Comment by jbaber** [comment]
Can we do the one time work in the background immediately at startup?  If the user tab-completes before the new one-time work is done, they could get results from the previous session's saved off database or something.  Or somehow steal whatever bash uses.  If tab completion right at the shell felt like this, users would complain heartily.

As a recent visitor from ratpoison, this behavior is really jarring.

**Comment by dbjergaard** [comment]
Finding out what bash does is a bit more code archaeology than I want to do. 

We already have threads and this is a pretty straightforward application. We just need a mutex around the hash table and some code to refresh the hashes. This can be launched from start up and the work will be done in the background. 

I don’t want to save the hash table to disk because of synchronization issues.

**Comment by dbjergaard** [comment]
There was an unnecessary sort which, when removed, speeds things up nicely.
