### ISSUE TITLE
Procedure execution in defcommand entry parameters

### ISSUE THREAD

**Issue by Whalehunter** [stumpwm/stumpwm#477]
Let's say I want to concatenate a string in the entry parameter string:
```lisp
(defun info-needed ()
    "some info")

(defcommand do-something (param1)
    ((:string (concatenate 'string "Info needed '" (info-needed) "' now insert some shit:"))))
```
Is there a way to make this possible. The error now says that the value has to be of type `CHARACTER` to be put in a character array. Now, that's the part I don't get, maybe because I'm fairly new to Lisp, but a string literal _is_ possible.

**Comment by sdilts** [comment]
The actual error message is more helpful:
```
The value
  CONCATENATE
is not of type
  CHARACTER
when setting an element of (ARRAY CHARACTER)
```
The second item in the `(TYPE PROMPT)` clause in `defcommand` expects a string literal, not an expression. Its trying to use the symbol `CONCATENATE` instead of evaluating the given expression.

I take it you want to call `info-needed` every time the command is run so that the prompt is rebuilt each call?  You can use the function `read-one-line` to get what you want.
``` lisp
(defcommand do-something () ()
  (let ((answer (read-one-line (current-screen)
			       (concatenate 'string "A string"
					    (info-needed)
					    "Another string"))))
    ;; do some stuff with with the answer:
    (print answer)))
```
If you need the interactive/non-interactive behavior of `defcommand` in addition to this, that is another story.

**Comment by Whalehunter** [comment]
@sdilts 
The proposed workaround solves my original problem, thanks.
But, to be clear, forcing a string literal in the `(TYPE PROMPT)` clause is a feature and not a bug?

Thanks for the help.

**Comment by jorams** [comment]
Whether you can consider it a feature I don't know, but it's not a bug. The `prompt` argument is meant to offer a hint to the user when they have not supplied a value for the argument yet. What that argument means should generally be static, so a simple string should be enough.
