### ISSUE TITLE
unable to compile: RR-GET-OUTPUT-INFO not in :XLIB package

### ISSUE THREAD

**Issue by szos** [stumpwm/stumpwm#576]
after git pull-ing StumpWM, I'm unable to recompile. All is well until running make, where it complains about XLIB::RR-GET-OUTPUT-INFO not existing in the XLIB package. The specific lisp form that is complained about is in head.lisp, on line 44, as part of a multiple-value-bind:
`(xlib::rr-get-output-info *display* output (get-universal-time))`
the debugger invocation message is:
`debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
 #<THREAD "main thread" RUNNING {hexadecimal number}>:
       COMPILE-FILE-ERROR while compiling <CL-SOURCE-FILE "stumpwm" "head">`

I think this is related to pull request #570, as the line in question ends up getting called from the randr branch of the cond statement found on line 71 of head.lisp. 

I got it to compile by commenting out the randr branch of the cond statement alongside the functions `make-screen-randr-heads` and `output->head`. However I havent attempted to run it. I assume that it will still work, as the xinerama branch is still there and the pull request that added this functionality is recent. 
this is on Manjaro linux, with SBCL.

**Comment by PuercoPop** [comment]
What version of CLX are you using?

**Comment by szos** [comment]
In `quicklisp/dists/quicklisp/software/` I have `clx-20170516-git`, `clx-xembed-20120909`, and `clx-truetype-20160825`. I'm not sure how to update these, I've always just relied on `ql:quickload` to get things.

**Comment by brettgilio** [comment]
Hi, I am able to reproduce this issue using ASDF

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "stumpwm" "head">)))

 error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
0] 15

The regression was introduced on the first February merge. So, this definitely isn't isolated.

I am using GuixSD as my GNU/Linux system building against SBCL.

**Comment by sdilts** [comment]
@szos You can update your quicklisp distributions by running `(ql:update-all-dists)` to update all of them, or individually with `(ql:update-dist dist-name)`,

@brettgilio The version of `clx` bundled with guix is really old. The commit shown for that package in the guix definition is from 2017 and can be found at https://github.com/sharplispers/clx/commit/1c62774b03c1cf3fe6e5cb532df8b14b44c96b95. If you want me to, I 'd be willing to submit a patch to guix to get it updated. For reference, the relevant configuration starts at line [916 in /gnu/packages/lisp.scm](http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/lisp.scm#n916)

This should be fixed by updating to the latest versions of `clx` as stated above, as the quicklisp version of `clx` found at https://github.com/sharplispers/clx/ contains this function. You can see its definition [here](https://github.com/sharplispers/clx/blob/33468982052ccd575b091520bec194c711d87af8/extensions/randr.lisp#L574-L602).

**Comment by szos** [comment]
Updating quicklisp dists fixed the problem, with clx-20181210-git. I'm closing this as a solution has been found.

**Comment by brettgilio** [comment]
@sdilts That is up to you, if you are comfortable working with Guix and our patching system please by all means submit a patch. It seems you are correct, and if you do submit a patch please change the version to reflect the stable release from february 4th rather than a commit id. The commit on february 4th seems to resolve this issue.

If you would prefer I submit the patch, I will do so.

Let me know, thanks again.

**Comment by sdilts** [comment]
You can find the patch I submitted here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34507.

**Comment by coolmedium** [comment]
I'm experiencing this issue as well. Building with SBCL version 1.5.1 on Ubuntu 18.04 (well, Pop!_OS)

```
CL-USER> (ql:update-all-dists)
1 dist to check.
You already have the latest version of "quicklisp": 2019-03-07.
NIL
CL-USER> (ql:quickload "stumpwm")
To load "stumpwm":
  Load 1 ASDF system:
    stumpwm
; Loading "stumpwm"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "RR-GET-OUTPUT-INFO" not found in the XLIB package.
;   
;       Line: 44, Column: 30, File-Position: 1503
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/cm/quicklisp/dists/quicklisp/software/stumpwm-20190307-git/head.lisp" {1003AF12D3}>
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1003B9EAB3}>.
CL-USER> 
```

**Comment by M4rkD** [comment]
I'm seeing the same issues as this with Ubuntu 18.04. Running the distutils command doesn't seem to work. I'm using sbcl installed through apt, and stumpwm installed by quicklisp.

Did you manage to resolve this issue?

**Comment by PuercoPop** [comment]
@M4rkD I'm running Ubuntu 18.04 as well although my SBCL is compiled from source and I run StumpWM from the git repo using cl-launch. I'm fairly certain that the issue is an old version of the CLX.

Can you paste the output of `(ql:where-is-system "clx")`? And just in case paste the contents of clx.asd there should be a `(:module "extensions" :components (... (:file "randr"))` in there.

**Comment by M4rkD** [comment]
```
* (ql:where-is-system "clx")

#P"/usr/share/common-lisp/source/clx/"
```

and in clx.asd
```

     (:module extensions
              :pathname #.(make-pathname :directory '(:relative))
              :components
              ((:file "shape")
               (:file "big-requests")
               (:file "xvidmode")
               (:xrender-source-file "xrender")
               (:file "glx")
               (:file "gl" :depends-on ("glx"))
               (:file "dpms")
               (:file "xtest")
               (:file "screensaver")
               (:file "xinerama")))
     (:module demo
      ...
```

**Comment by M4rkD** [comment]
Pardon the ignorance, but how can I upgrade clx if ` (ql:update-all-dists) ` doesn't work?

**Comment by PuercoPop** [comment]
> Pardon the ignorance

@M4rkD Don't worry, its not your ignorance, its the awful lisp packaging from Ubuntu. `(ql:update-all-dists)` is working but the distro package of SBCL is configuring ASDF search paths and they are taking precedence over the search paths configured by quicklisp (quicklisp delegates to ASDF the loading of packages, only when ASDF doesn't find a package does it try to download it).

I'm also partially to blame, I've been meaning to update the README and issue templates to warn against using distro packages for Lisp for a while but I haven't gotten around to it yet.

I recommend you compile your SBCL from source and remove the SBCL you install through apt-get. Because SBCL requires a CL compiler to compile itself don't remove the version from Ubuntu until you compile it. The process is as follow 

```
cd ~/code
git clone git@github.com:sbcl/sbcl.git
cd sbcl
sh make.sh --prefix=/usr/local --fancy
<take note of the installation instructions printed to your terminal here but don't run them yet>
apt-get remove sbcl
apt-get purge sbcl
<follow the installation instructions>
```

A couple of notes, the prefix is optional, I placing things I installed from source in `/usr/local/` so there is never a conflict with whatever apt-get installs. I'm fairly certain the installation instructions are `sudo make install` but the command may be a little different, its the moral equivalent anyway. Its not necessary to build the documentation but do so if you like info manuals.

Afterwards rebuild StumpWM and you should be good to go. Let me know if I you have any doubts.

**Comment by alexanderbarbosa** [comment]
@PuercoPop 

No need to remove system sbcl install, as all distro look for $HOME>/usr/local>/usr/bin in $PATH.

Just install it alongside

**Comment by Fruchtenstein** [comment]
I've just solved the same issue by removing the system package cl-clx-sbcl (Debian Buster).

**Comment by alexanderbarbosa** [comment]
@Fruchtenstein 

Yep. Debian cl-xxxx packages are usually outdated for more than a year....

**Comment by heroxbd** [comment]
Hi, now stumpwm is updated in Debian.  Welcome to install it with `apt install stumpwm`.
