### ISSUE TITLE
select-from-menu non-closing menu

### ISSUE THREAD

**Issue by jamesmccabe** [stumpwm/stumpwm#582]
Would it be possible to have a select-from-menu that doesn't close the menu when RET selects a choice? It would just use ESC to abort/close. When RET was pressed on a highlighted menu entry it would just execute it without closing the menu. This would be useful for a volume menu or a layouts menu.

I know this is probably trivial to implement with the current select-from-menu but I have tried unsuccessfully to get a menu working like this using *mytest-menu-map* and binding RET to a function or defmethod like [menu-finish](https://github.com/stumpwm/stumpwm/blob/master/menu-definitions.lisp#L146). Any ideas would greatly appreciated. My lisp skills are rudimentary.

**Comment by sdilts** [comment]
To do this, you need to change the contents of the keymap so that `RET` is no longer bound to `menu-finish`, but bound to another function. This is what the `extra-keymap` parameter is for. The keymap given in this parameter takes precedence over the default, so the solution is fairly straightforward: just make a new keymap with your customizations, and pass it to `select-from-menu`. Here's an example:
``` lisp
(let ((custom-map (make-sparse-keymap)))
  (define-key custom-map (kbd "RET") (lambda (menu)
			                (print (menu-selected menu))))
  (select-from-menu (current-screen) (list "a" "b" "c")
		    "Print to console" 0 custom-map))
```
This code is crying out for some abstraction into a function called `execute-from-menu`. There are two ways to fix this: wrap the above code into the function and call it a day, or subclass either `single-menu` or `menu` and write your method specializations and your `execute-from-menu` function. Frankly, I'd just go for the first option as it is much simpler, but the second has some benefits too. If you think this would be a good addition to stumpwm, the second option is probably the way to go.

To go the second route, you would only need to write an `initialize-instance` method for your new class that includes your new keymap. Check out the `initialize-instance` method for each menu class to see how they add their keymaps on top of `*menu-map*`. Since `read-from-keymap` accepts a list of keymaps, all you need to do is add the execution menu keymap to the `keymap` slot in the menu class. Your `execute-from-menu` function should look fairly similar to `select-from-menu`.

**Comment by jamesmccabe** [comment]
I have this in my test menu. My problem is the `execute-from-menu` function.
I don't know how to execute the chosen list item. I have this:

```lisp
(defun execute-from-menu (test)
  ;; ToDo: execute choice list item...................)

(defvar *test-menu-map* nil)
(when (null *test-menu-map*)
  (setf *test-menu-map*
        (let ((m (make-sparse-keymap)))
          (define-key m (kbd "RET") 'execute-from-menu)
          m)))

(defvar *table*
  '(("VOL UP" "volume-increase")
    ("VOL DOWN" "volume-decrease")
    ("TOGGLE MUTE" "toggle-mute")))

(defcommand stump-test-menu () ()
  (let ((choice (second
      (select-from-menu (current-screen)
                        *table*
                        nil
                        0
                        *test-menu-map*))
    
(define-key *top-map* (kbd "s-F2") "stump-test-menu")
```
I want to execute `volume-increase`, `volume-decrease` or `togglemute` functions.
I guess I need something similar to the `menu-finish` function except it does not throw a `:menu-quit`. Please excuse my lisp skills.

**Comment by sdilts** [comment]
The `execute-from-menu` function is passed a menu object that holds the state of the menu. You can use this object to extract the currently selected item. That code looks like:
``` lisp
(nth (menu-selected menu-object) (menu-table menu-object))
```
This will give you one of the elements in your `*table*` list You want the second item in the selected element, which can be retrieved with the `second` function. Finally. you can run the command using the `run-commands` function. This is the final code:
``` lisp
(defun execute-items (menu-object)
  ;; let* allows us to use variables previously declared in the let binding:
  (let* ((selected-entry (nth (menu-selected menu-object) (menu-table menu-object)))
	 (function-to-run (second selected-entry)))
    ;; based on the value of the *table* variable, function-to-run
    ;; now has one of these values: "volume-increase", "volume-decrease", or "toggle-mute"
    ;; Since these values are strings and not function objects, we need to use stumpwm's
    ;; run-commands function instead of apply or funcall
    (run-commands function-to-run)))
```
To get a better understanding of what this is doing, stick some calls to [DESCRIBE](http://clhs.lisp.se/Body/f_descri.htm#describe) various places in the function. For example, you could insert `(describe menu-object)` to print out everything stored in the menu object.

**Comment by jamesmccabe** [comment]
Thats exactly what I was looking for!! Thanks @sdilts ! I was messing with this for weeks.
I understand what it is doing from your variable names. It looks easy now :+1: .

I will leave it up to you about including in the Stump source. It probably doesn't need to go in there. I guess this issue can be closed as the problem has been solved.

**Comment by jamesmccabe** [comment]
I will close this issue as the problem has been resolved.
