### ISSUE TITLE
stumpwm doesn't recongize xmodmap modified keycode

### ISSUE THREAD

**Issue by dingyi342** [stumpwm/stumpwm#621]
I use semicolon as a modifier key with the help of xmodmap.
My ~/.Xmodmap file
keycode  47 = Mode_switch Mode_switch Mode_switch
keycode  40 = d D colon U0394

(defcommand emms () ()
  "emms"
  (emacs)
  (send-meta-key (current-screen) (kbd "M-:"))
  (window-send-string "(stumpwm/emms)")
  (send-meta-key (current-screen) (kbd "RET"))
  )

When I eval (emms), It reports me:
The value NIL is not of type (UNSIGNED-BYTE 8) when binding XLIB::KEYCODE

If I don't use my xmodmap config, it runs normally.

**Comment by PuercoPop** [comment]
@dingyi342 Hi, If I'm understandly correctly you are expecting `(kbd "M-:"`) to be equivalent as if you pressed meta and the semi-colon key in your keyboard? 

What appears to be happening is that StumpWM isn't finding the colon key in `*name-keysym-translations*` because it is on a modifier key (which would be a bug in StumpWM imho). Could you paste the output of running `(gethash "colon" stumpwm::*name-keysym-translations*)`?

**Comment by dingyi342** [comment]
All outputs "58 T".
I can input colon everywhere with ;-d, also combiation with modifiers.
But, I use "describe-key" command with ;-d , it outputs:
SunAltGraph is not bound.
