### ISSUE TITLE
send-meta-key doesn't work in terminator/IDEA

### ISSUE THREAD

**Issue by dingyi342** [stumpwm/stumpwm#624]
```
(defcommand paste () ()
  (send-meta-key (current-screen) (kbd "S-Insert"))
  )

(define-key *top-map* (kbd "s-v") "paste")
```
It works in many program, except Guake(terminal) and IDEA.

**Comment by alexanderbarbosa** [comment]
and how is that related to stumpwm?

**Comment by dingyi342** [comment]
It did not say which window could not be used, so I thought it was an issue. Otherwise, please state which kind of window could not be used in the function description.

**Comment by dingyi342** [comment]
@alexanderbarbosa It did not say which window could not be used, so I thought it was an issue. Otherwise, please state which kind of window could not be used in the function description.

**Comment by PuercoPop** [comment]
@dingyi342 what I think @alexanderbarbosa is trying to say is why do you consider this a StumpWM issue instead of an issue with Guake or IDEA given that you says it works in other programs so the keys _are_ being sent.

**Comment by tpine** [comment]
While I don't have the issue with terminator I have had previous issues with DBeaver blocking the prefix key on every computer I use from being sent. I haven't reported it for the same reason @alexanderbarbosa said in that it seemed to be a issue with just the program.

 But DBeaver and IDEA are both java programs so maybe there is a common link with java programs causing some issues with the handling of keyboard input due to some semi-common mistake while writing them?

**Comment by alexanderbarbosa** [comment]
@tpine 

It might help you: export _JAVA_AWT_WM_NONREPARENTING=1

**Comment by dingyi342** [comment]
@PuercoPop EXWM works with the function 'exwm-input--fake-key', so I think STUMPWM also can do it. Sometimes Exwm is too slow, so I try Stumpwm.

**Comment by dingyi342** [comment]
```
(defcommand mysend () ()
  (run-shell-command "xdotool key shift+Insert")
  )
```
It works.
