### ISSUE TITLE
StumpWM spontaneous crash in XWIN-NAME

### ISSUE THREAD

**Issue by shamazmazum** [stumpwm/stumpwm#641]
Hello. After system update (I've updated both xorg libraries and quicklisp repo) I am constantly receiving spontaneous crashes at random time. As I lose connection to my X environment, I cannot copy-paste backtrace for you, so I attach a picture (very sorry for this):
[Backtrace photo](https://i.postimg.cc/RV3qmPLx/IMG-20190907-093609.jpg)

How can this be fixed? 

UPD: As you can see, my stumpwm is in local-projects. I use my own fork of stumpwm, which has truetype fonts patch included and supports wallpapers. It is almost up to date with upstream.

UPD2: Seems like a bug in clx, but I report here anyway, because I do not know how to reproduce it without stumpwm. Also, maybe bug appears when I have non-ASCII characters in window names? Could be. Will check it

**Comment by shamazmazum** [comment]
I was right. The bug appears when there are some windows with non ASCII-characters (like russian letters) in their names. Strange, this bug has showed up only recently.

**Comment by PuercoPop** [comment]
> Strange, this bug has showed up only recently.

It is likely due to the increased safety in clx's compilation options, which is a good thing.

> How can this be fixed?

I think I've spotted the issue. If I'm reading the code for `xwin-name` correctly only reading the window name from :_NET_WM_NAME is utf8 aware. Can you try modifying [xwin-name](https://github.com/stumpwm/stumpwm/blob/8c6bf7e5f9e4905dad83c7b6c4c7f3aab2a69652/window.lisp#L337) slightly?

```lisp
(defun xwin-wm-name (win)
  "Return the netwm wm name"
  (when-let ((name (xlib:get-property win :WM_NAME)))
    (utf8-to-string name)))

(defun xwin-name (win)
  (escape-caret (or (xwin-net-wm-name win)
                    (xwin-wm-name win)
                    "")))
```

let me know if it works

**Comment by shamazmazum** [comment]
@PuercoPop, Hi.

Reporting. StumpWM no longer crashes, but decodes some window titles (which are decoded by xwin-wm-name, obviously) incorrectly.

For example it returns "С????к ??амб??ка в XI Ча??ов - Снежн??й ????д" instead of "Стук Бамбука в XI Часов - Снежный Мёд".

This string converted by function (lambda (str) (map 'vector #'char-code str)):

#(1057 63 63 63 63 1082 32 63 63 1072 1084 1073 63 63 1082 1072 32 1074 32 88
  73 32 1063 1072 63 63 1086 1074 32 45 32 1057 1085 1077 1078 1085 63 63 1081
  32 63 63 63 63 1076)

Other windows have their titles obtained and rendered correctly.

**Comment by shamazmazum** [comment]
BTW, xprop also does not understand WM_NAME. See two examples:

> vasily@vonbraun:~ % xprop | grep NAME
WM_LOCALE_NAME(STRING) = "ru_RU.UTF-8"
WM_ICON_NAME(STRING) = "Ð¡Ñ?Ñ?Ðº Ð?Ð°Ð¼Ð±Ñ?ÐºÐ° Ð² XI Ð§Ð°Ñ?Ð¾Ð² - Ð¡Ð»Ð°Ð±Ñ?Ð¹ Ð¢Ð¸Ð³Ñ?"
WM_NAME(STRING) = "Ð¡Ñ?Ñ?Ðº Ð?Ð°Ð¼Ð±Ñ?ÐºÐ° Ð² XI Ð§Ð°Ñ?Ð¾Ð² - Ð¡Ð»Ð°Ð±Ñ?Ð¹ Ð¢Ð¸Ð³Ñ?"
vasily@vonbraun:~ % xprop | grep NAME
WM_NAME(UTF8_STRING) = "Новая вкладка - Iridium"
_NET_WM_NAME(UTF8_STRING) = "Новая вкладка - Iridium"
WM_LOCALE_NAME(STRING) = "ru_RU.UTF-8"

[This](https://stackoverflow.com/questions/7706589/is-there-any-difference-with-the-x11-atoms-xa-wm-name-and-net-wm-name) is what I found after some googling. It seems that the application (uxterm) misuses WM_NAME, putting UTF-8 encoded string in this property. Am I right? What can be done about it?

**Comment by PuercoPop** [comment]
Ok, I've digged a little bit into ICCM and I have a proper fix in mind I'll send the PR which I'll ask you to test before merging. 

The [iccm spec](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.1) states:

> The WM_NAME property is an uninterpreted string

> The encoding used for this string (and all other uninterpreted string properties) is implied by the type of the property.

So it is an error on clx's side to assume that WM_NAME is of encoded as a  `STRING`.

>  It seems that the application (uxterm) misuses WM_NAME, putting UTF-8 encoded string in this property. Am I right?

It is not a misuse, which is why xprop shows the utf8_string as the type of WM_NAME.

> What can be done about it?

At the very minimum we should handle the decoding error and return nil so we can default to the empty string. It is not ok to crash. The proper fix is for us to decode the string according to the encoding indicated in their property type. The property type of is returned as the second value of xlib:get-property. ej.

> STUMPWM> (xlib:get-property #v6 :WM_NAME)
> (116 109 117 120)
> :UTF8_STRING
> 8 (4 bits, #x8, #o10, #b1000)
> 0 (0 bits, #x0, #o0, #b0)
> STUMPWM>

**Comment by PuercoPop** [comment]
@shamazmazum please try out this branch

https://github.com/stumpwm/stumpwm/issues/641

**Comment by shamazmazum** [comment]
@PuercoPop No, this does not fix it. Please look at output of xprop I posted above. I post it here too:
>vasily@vonbraun:~ % xprop | grep NAME
WM_LOCALE_NAME(STRING) = "ru_RU.UTF-8"
WM_ICON_NAME(STRING) = "Ð¡Ñ?Ñ?Ðº Ð?Ð°Ð¼Ð±Ñ?ÐºÐ° Ð² XI Ð§Ð°Ñ?Ð¾Ð² - Ð¡Ð»Ð°Ð±Ñ?Ð¹ Ð¢Ð¸Ð³Ñ?"
WM_NAME(STRING) = "Ð¡Ñ?Ñ?Ðº Ð?Ð°Ð¼Ð±Ñ?ÐºÐ° Ð² XI Ð§Ð°Ñ?Ð¾Ð² - Ð¡Ð»Ð°Ð±Ñ?Ð¹ Ð¢Ð¸Ð³Ñ?"

It's clearly Uxterm bug, as it puts UTF-8 string in a property of type STRING. I think we should wrap decoding in handler-case form (or what you think is appropriate) to catch the decoding error.
