### ISSUE TITLE
StumpWM crashes frequently when switching monitors

### ISSUE THREAD

**Issue by sjl** [stumpwm/stumpwm#647]
Sorry for this long, rambling issue, but I don't really understand what's happening and/or know how to debug it further.

I use StumpWM on two different machines:

* A desktop PC that's always attached to a single monitor.
* A laptop that is sometimes used on its own, and other times used with an external monitor.

The desktop setup is fine.  The laptop, however, has gotten extremely flaky when switching between the laptop monitor and the external monitor.  I have two commands set up in my `stumpwmrc` to run the necessary `xrandr` commands to switch between the setups:

```lisp
(defcommand screen-laptop () ()
  (loop with laptop = "eDP1"
        with extern = "DP1"
        for (output commands) in `((,laptop ("--auto"))
                                   (,laptop ("--primary"))
                                   (,extern ("--off")))
        do (uiop:run-program `("xrandr" "--output" ,output ,@commands))))

(defcommand screen-external () ()
  (loop with laptop = "eDP1"
        with extern = "DP1"
        for (output commands) in `((,extern ("--auto"))
                                   (,extern ("--primary"))
                                   (,laptop ("--off")))
        do (uiop:run-program `("xrandr" "--output" ,output ,@commands))))
```

These used to work fine, but last week I updated StumpWM and SBCL and now running these commands seems to crash StumpWM pretty often (I'd say ~50% chance of crashing).  I was previously on StumpWM commit 6115981 and am now on commit ae97bf9 and I'm using SBCL 1.5.6.

Here are some photos of the kinds of errors I get (the `copy-unhandled-error` command mentioned in the text box doesn't seem to work, so phone pictures are all I've got, sorry).  First, the error I usually see is this:

![Photo Sep 11, 13 38 06](https://user-images.githubusercontent.com/58365/64815755-490ca980-d574-11e9-9df1-b5650de808ff.jpg)

I tried sniffing around in the code and hacking in a fix:

```diff
diff --git a/tile-group.lisp b/tile-group.lisp
index eeea233..296b8cd 100644
--- a/tile-group.lisp
+++ b/tile-group.lisp
@@ -128,9 +128,10 @@
 (defmethod group-lost-focus ((group tile-group))
   ;; If this window had the focus, try to avoid losing it.
   (let ((frame (tile-group-current-frame group)))
-    (setf (frame-window frame)
-          (first (remove-if 'window-hidden-p (frame-windows group frame))))
-    (focus-frame group frame)))
+    (when frame
+      (setf (frame-window frame)
+            (first (remove-if 'window-hidden-p (frame-windows group frame))))
+      (focus-frame group frame))))
 
 (defmethod group-indicate-focus ((group tile-group))
   (show-frame-indicator group))
```

Which prevents that error, but then I start getting different errors:

![Photo Sep 11, 13 48 52](https://user-images.githubusercontent.com/58365/64815884-896c2780-d574-11e9-9d4c-953f92deb454.jpg)

I stopped looking at the code there because I really don't understand what's going on, and don't just want to duct-tape in a fix that doesn't make sense.

Also, sometimes instead of giving me a backtrace StumpWM will just completely hard crash me back to the display manager.  I have no idea how to figure out what's happening there -- are there any logs I might want to look at or something?

If I manually run the `xrandr` commands in a shell, I don't (as far as I can tell) get the errors.  However, some things still seem to be a bit flaky (e.g. some of the frames are weirdly overlapping until I run `:only` to blow everything away and start from scratch).  Maybe I need to `(sleep 2)` between the commands or something?

I guess my next step will be to `git bisect` the last year's worth of commits and try to find the one that created this brittleness.  I just haven't gotten around to that yet because bisecting a WM-crashing bug is probably going to be painful, and this only happens on my work laptop, where I need to be doing actual work instead of fiddling with Linux stuff.

(Yes, I know I should update more often, but I find myself avoiding updating software because something always breaks whenever I do (example: this).)

**Comment by kriyative** [comment]
I ran into the same issue upgrading from 744e53d to 47c3923. I narrowed the issue to commit 84a541c9cc2081dafef590f0c0411f7e3a5e748e from Feb 14, 2019. If I disable the `cond` clause which uses `make-screen-randr-heads` [1] the issue goes away.

I have not had time to debug exactly what is going wrong in the new code is, but for now the following workaround has stopped stumpwm from crashing when adding/removing external displays:

```
diff --git a/head.lisp b/head.lisp
index 33ec85b..2a1eddc 100644
--- a/head.lisp
+++ b/head.lisp
@@ -69,8 +69,8 @@
 
 (defun make-screen-heads (screen root)
   (declare (ignore screen))
-  (cond ((xlib:query-extension *display* "RANDR")
-         (make-screen-randr-heads root))
+  (cond #+nil ((xlib:query-extension *display* "RANDR")
+               (make-screen-randr-heads root))
         ((and (xlib:query-extension *display* "XINERAMA")
               (xinerama:xinerama-is-active *display*))
          (mapcar 'screen-info-head
```

[1] https://github.com/stumpwm/stumpwm/blob/master/head.lisp#L72

**Comment by sjl** [comment]
That workaround does stop the problem for me.  Thanks for tracking down the issue more carefully than I did.

**Comment by kriyative** [comment]
@sjl @PuercoPop - I dug into this a bit more and think this is due to implementation issues in `xlib:rr-get-output-info` [1].

For now, I could create a PR which adds `(defvar *enable-randr-extension* nil)` and short-circuit the `xlib:query-extension` based on whether it's set to `t`. What do you think?

[1] https://github.com/sharplispers/clx/blob/master/extensions/randr.lisp#L578

**Comment by sjl** [comment]
I don't think I know enough about what `randr` and `xinerama` to have a valid opinion here.

**Comment by kriyative** [comment]
I'm hoping @ralt, who originated the `randr` based detection commit, could add some context to this discussion.

@ralt  - Any pointers on what the underlying cause could be? ... I presume the `randr` based detection works for you and others, or we'd be hearing more complaints.

I don't know what the trade-offs over `xinerama` are either. Since the underlying clx code seems to indicate that there are known issues, should we a `*enable-randr-extension*` like config to conditionally enable this feature?

**Comment by kriyative** [comment]
I've added a PR for the config variable. Please note, I've defaulted the setting to `nil` which is different from current behavior. I figure it's better to have a stable default experience instead of the current unpredictable crashes.

**Comment by PuercoPop** [comment]
@kriyative Sorry for the late reply. I personally dislike the idea of a feature flag but that is @dmb2 to make. Either way thanks for going the extra mile and submitting a PR with your proposed fix :tada:.

If the problem is the implementation in CLX we should fix that instead. One thing that this highlights is that we need a better logging mechanism.

I currently don't use multiple monitors but have done so in the past so I can vouch that @ralt's change works. We have seen but reports about StumpWM crashing when no monitor is connected but https://github.com/stumpwm/stumpwm/pull/611 should have taken care of it.

One thing I don't have clear is what does CRTC means in the context of randr.
