### ISSUE TITLE
Prefix map breaks C-x C-t on Emacs

### ISSUE THREAD

**Issue by aadcg** [stumpwm/stumpwm#657]
C-x C-t (transpose-lines) is often used in Emacs. Since Stumpwm is the "Emacs of window managers", I wonder if the default prefix map shouldn't be redefined by default so that it doesn't break Emacs' commands.

I know how to fix this: either remap transpose-lines or choose another prefix map.

My point is if this doesn't contradict the philosophy of stumpwm.

**Comment by xsteve** [comment]
Well, emacs has bound a lot of keybindings. And the important ones differ from user to user.

I solved this problem long ago by setting my own prefix key:

;; Change the Stumpwm prefix key: Use the menu key
(set-prefix-key (kbd "Menu"))

This has another advantage that it is a single key. The prefix key of stumpwm must be easy to type.
Since it is fully configurable I don't mind the default.

**Comment by aadcg** [comment]
Fair enough. I'm closing this.

**Comment by aadcg** [comment]
Fair enough. I'm closing this.

**Comment by Harleqin** [comment]
Also, if my memory serves right, `C-t t` sends a `C-t` to the active frame in the default map.
