### ISSUE TITLE
[Queries]: Miscellaneous question to create pre-defined session with stumwpm

### ISSUE THREAD

**Issue by rowhit** [stumpwm/stumpwm#662]
# Launch application in predefined group
I am not sure if this feature is already there in the stumpwm. However, I could not find anything in the documentation directly pointing to this. In the init.lisp file if I do the following:
```lisp
(stumpwm:run-commands "gnew group1")
(stumpwm:run-shell-command "terminator --working-directory=/projects/group1/")
(stumpwm:run-commands "gnew group2")
(stumpwm:run-shell-command "terminator --working-directory=/projects/group2/")
````
The above creates two groups as specified group1 and group2. However, two terminator applications open in group2, as it is the last one. I am not sure how to force the application to open in the desired group. This is primarily happening due to the delay in opening the applications.

# Application Window Control and Commands
I have few more related queries:
- How do I name the application window?
- How to send command to the application window form init.lisp?

# Swank/Slime Server
- How to escape the clisp error when accidentally a wrong command is sent over the swank server through slime client?
- If for some reason the server gets killed in the stumpwm, how to restart without restarting the xsession.
- Can you create multiple swank servers in single stumpwm sessions?

I am new to common lisp world, so please pardon if some queries are basic.

**Comment by defaultxr** [comment]
The reason both terminators appear in the second group is probably because there is a slight delay to them opening, but stump's delay in creating a group is much smaller. So both groups are created before either terminator appears.

To specify which group a program opens in, [define-frame-preference](https://stumpwm.github.io/git/stumpwm-git_5.html#index-define_002dframe_002dpreference) is your best bet. For example:

```lisp
(define-frame-preference "group2"
  (0 nil t :role "terminator-group2"))
```

This will make any program with the "terminator-group2" role as the title appear in `group2`. Looks like you can launch terminator with a custom "role" using a command like so:

`terminator --role='terminator-group2'`

This should make it so that only that terminator instance will be opened in group2.

> How do I name the application window?

Use the [title](https://stumpwm.github.io/git/stumpwm-git_5.html#index-title) command/function.

> How to send command to the application window form init.lisp?

The [window-send-string](https://stumpwm.github.io/git/stumpwm-git_13.html) function.

> How to escape the clisp error when accidentally a wrong command is sent over the swank server through slime client?

Not sure about that, did you try `C-g`?

I'm also not sure about your last two questions, sorry.
