### ISSUE TITLE
gselect 1, 2, 3... should make a new group if there is not one there already

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#697]
Trying to open one of these groups returns a message "No Such Group."

I propose a condition `no-such-group` being defined, which can be used in this exceptional situation to be handled as `gnew "workspace N"` instead.

In fact there are a lot of [calls to `throw 'error`](https://github.com/stumpwm/stumpwm/search?q=throw+error&unscoped_q=throw+error&type=Code) that could possibly be made useful.

Also, these prompt the user for a group, which makes no sense. They should just open the group at the number without prompting. Try: `C-t <F1>` so see the prompt.

Also, `gmove` and should do the same thing.

**Comment by dmb2** [comment]
No, this changes default behavior.  This is a case where your expected behavior isn't how it works, but it isn't clearly what everyone might expect.  Opening/selecting a non-existant group should return said message.

Opening a new group should prompt the user for the group name unless it was supplied from a non-interactive call (this is currently correctly handled).
