### ISSUE TITLE
C-t h ... doesn't work

### ISSUE THREAD

**Issue by YorkZ** [stumpwm/stumpwm#736]
Pressing `C-t h ...` doesn't seem to work. My StumpWM version is `1.0.1`.

**Comment by PuercoPop** [comment]
@YorkZ Could you be more specific? What key combination doesn't work? I'm currently running master and it does work for me.

Also 1.0.1 is a ~2 year old release, the latest one is 19.11 (we are using YY.MM for versions since last year)

**Comment by YorkZ** [comment]
@PuercoPop Thank you for trying to help. Regarding the `StumpWM` version I'm using, I got the version number by typing `C-t ; version`. I installed it from `quicklisp` by:
```
(ql:quickload "stumpwm")
```
So no `C-t h KEY` key combination work for me. For example, when I type `C-t hk`, it feels like the `C-t h` key was eaten, and the letter `k` was typed in; and so do `C-t h f`, `C-t h v`, `C-t h w` and `C-t h c`.

Please let me know how I could help digging, I'm also interested in taking this as an opportunity to learn a bit more about `StumpWM` internal.

**Comment by YorkZ** [comment]
So is `StumpWM` from `quicklisp` the proper version to use?

**Comment by PuercoPop** [comment]
@YorkZ sorry for the late reply

> Please let me know how I could help digging, I'm also interested in taking this as an opportunity to learn a bit more about StumpWM internal.

If you want to use this as an opportunity to start hacking in StumpWM I recommend you first setup StumpWM so you can connect to it through SLIME/Sly. There are some instructions in the [wiki](https://github.com/stumpwm/stumpwm/wiki/Hacking-StumpWM#emacs). Let me know if you run into any trouble. I personally use Sly but other people use SLIME.

Once you've done you'll need to track the what is going wrong. In this case we want to check that the keymap is indeed calling the commands you expect and that the commands work as expected. In this case, because it doesn't appear that any help command is called start by verifying that the variable `*help-map*` has the appropriate bindings. Then make sure that the `*help-map*` is bound in the `*root-map*`. If you run the following snippet `(find "*help-map*" (kmap-bindings  *root-map*) :key 'binding-command :test #'string-equal)` it should return something like

```
#S(BINDING
   :KEY #S(KEY
           :KEYSYM 104
           :SHIFT NIL
           :CONTROL NIL
           :META NIL
           :ALT NIL
           :HYPER NIL
           :SUPER NIL)
   :COMMAND *HELP-MAP*)
```

Hope that is enough to get you started.

> So is StumpWM from quicklisp the proper version to use?

I'm not sure what proper means in this context but my recommendation is to use either the latest [release](https://github.com/stumpwm/stumpwm/releases) or master. If you want to hack on StumpWM I recommend you clone StumpWM into `~/quicklisp/local-projects/` and use that version.

**Comment by YorkZ** [comment]
Thank you so much @PuercoPop. I already had SLIME setup in my environment, therefore, I went directly to checking the binging of `*help-map*` in `*root-map*`. I then figured out that my bindings was 106 ("j") instead of 104 ("h") which I recall that I rebound it probably two years or so ago:
```
(define-key *root-map* (kbd "j") '*help-map*) ; was on 'h'
```
I totally forgot about this. I apologize about it, and thank you so much for your help.

By the way, to be convenient, I evaluated `(in-package :stumpwm)` in my `slime-repl` buffer, but how can I set it back to using the global name space? Also, `slime-edit-definition` can take me to any `stumpwm` symbol definition, but can't take me to non-stumpwm symbols like `defun` for example. How can I make it do so?
