### ISSUE TITLE
[FEATURE-PROPOSAL] Allow additional filter criteria when absorbing windows

### ISSUE THREAD

**Issue by setzer22** [stumpwm/stumpwm#737]
I'm trying to run stumpwm inside a KDE Plasma session. My current approach (the one that leads to less problems) is to kill kwin and start stumpwm. Stumpwm then absorbs all the existing X windows and is able to run normally.

Now, most things work, but there are several annoyances that I cannot get rid of using configuration code alone: 
- The "Plasma Destkop" ends up being a regular window, that's undesirable. The window should be left unmapped by stumpwm.
- Plasma seems to spawn two (most likely: one per monitor) "dummy" dock windows, each 270 pixels tall. I don't know what these windows are, but I don't want them to be added as modelines, even if they have the :dock flag set.

To fix this, I need to touch stumpwm's core (window.lisp, events.lisp). I'm opening this issue to see if the changes I'm making to stumpwm would be welcome as a pull request. Basically, I want to introduce the following changes:

- In `process-existing-windows` (window.lisp) and the `:map-request` event handler (events.lisp), run a list of filter functions on `win`. This list is initially empty and can be populated by the user. If any of the filters fail, the window is not absorbed (in the first case) or the map request is ignored (second case).

I think the changes may be welcome by other users in similar situations. Not all applications interact well with tiling window managers (mostly due to some flags not being properly set by the developers), so it is expected and needed to have some code in user config files that adds special rules for those applications.

**Comment by dmb2** [comment]
I will not support anything more than adding a hook in the right place for you to extend what you want. Desktop environments that include icons are usually implemented as you describe, they're windows that exist "below" the other windows an cannot be resized or moved.  The way stumpwm handles these windows is to map and manipulate them as if they are any other window. 

I'm not aware of anywhere in the FreeDesktop spec where we have to treat "desktop" windows specially.  (Although I'm no expert in the FreeDesktop spec).

I appreciate you opening an issue before implementing a solution since in this case, I have strong opinions about what I'm willing to merge into the main branch.

**Comment by setzer22** [comment]
No worries then. I think it will be best if I just keep the changes in my own branch. 

Please correct me if I'm wrong, but I think adding a hook would not solve my problem (unless there'd be way to tell stumpwm to "ignore" a window from the hook, that is).

Anyway, that's why this is a hackable window manager. It's been very easy to set up these changes myself. Thanks to the maintainers for that!
