### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by bijang** [stumpwm/stumpwm#739]
is there progress on wayland support?

**Comment by sdilts** [comment]
As far as I know, there are no efforts to port stumpwm to Wayland within Stumpwm proper. I looked into doing it last summer, and I'll share what I learned from the experience.

## Issues preventing a straightforward port
There are several issues with how Stumpwm is currently implemented that prevent porting Stumpwm to Wayland from a straightforward process. Many of the problems are related to outstanding or partially fixed issues, but they would require possible major re-engineering and/or incompatible API changes to fix. The other issues are related to the ecosystem surrounding Wayland and its related technologies in Common Lisp. I'm certainly not an expert in any of this and have developed a somewhat pessimistic viewpoint, but here are my observations:

### Stumpwm related problems:
1. Many of stumpwm's operations are blocking. While only an inconvenience with X11, I believe it would seriously hinder the drawing loop that a Wayland implementation needs to have.
2. Stumpwm's modeline and menu system are done in the same process as stumpwm using the same event loop. This greatly complicates the porting process and is just a weird (but somewhat justified) setup. There are much better solutions when using Wayland, such as the [layer shell protocol](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml).
3. There is a lot of global state that is specific to X11 that would need to be ripped out and abstracted. I don't know enough about how X11 works to say much beyond this.
4. Stumpwm makes heavy use of the X11 drawing primitives, which obviously aren't available in a Wayland compositor.

### Wayland Issues:
These issues essentially boil down to the fact that the bindings to the proper libraries to write Wayland compositors and applications are either severely out of date or don't yet exist, and creating them would take at ton of effort.
1. Wayland itself is a complicated beast that offloads much of the work that X11 does onto a compositor writer's plate. Thankfully, libraries like [wlroots](https://github.com/swaywm/wlroots) or [libweston](https://gitlab.freedesktop.org/wayland/weston) can do much of the work for us, but they are unstable and require a relative expert to use. Efforts like [adding the scene-graph API to wlroots](https://github.com/swaywm/wlroots/issues/1826) promise to help with some of these implementation issues, but it still has a long way to go.
   +  [ulubis](https://github.com/malcolmstill/ulubis) shows that not using a helper library is very possible, but would require many man hours to reach a stable implementation that would match the performance and stability of one of the helper libraries. There's a reason why wlroot's readme says that it is "about 50,000 lines of code you were going to write anyway."
2. As far as I can tell, the only part of wayland that is almost directly compatible with the way we do things in stumpwm is the keyboard input interface. Everything else would need to have an abstraction layer or separate implementations.

There are probably more issues that I'm forgetting, overlooking. or even blowing way out of proportion. 

## My recommendations for a Wayland implementation:
Due to these issues, I decided that the best way forward was to start from scratch, which I did with [Mahogany](https://github.com/sdilts/mahogany). After working on that for a while, here are my recommendations for writing a Wayland compositor in Common Lisp:
+ Use a small core written in C to setup the event loop, render output, and handle signals from connecting clients.  The Wayland helper libraries are too unstable and rely on enough pointer manipulation that writing an FFI wrapper for them isn't currently worth the time.
+ Write a backend in CL that abstracts away the C-isms in the core.
+ Write a front end that places windows, handles input, configures outputs, draws window borders, and everything else that the core doesn't take care of.

I'd love to restart development of Mahogany, or work on something in Stumpwm or Paulownia if there are enough interested contributors.

**Comment by bijang** [comment]
I hope you find the contributors, I think you should hack on regardless seems like youve great insight into what is required, and mahogony seems like a great base to build from scratch

**Comment by dmb2** [comment]
I largely agree with everything @sdilts has identified.  There's just too much in StumpWM's architecture that is dependent on CLX/X11.  I really like the idea of a core written in C that can be directly hooked into Lisp.  

Paulownia is pretty much dead.  The future is something written in Wayland for which large parts of stumpwm will not work.  I would like to keep keybindings and as much of the API the same, but the modeline is really in-extensible.  It would be great to have a widget base system that allowed more gui type things (clicking windows and a system tray).

**Comment by bijang** [comment]
Sounds like great ideas! Would it be worth writing a sketch of a feature list for what the planned or desired outcome would look like or have? Presumably most of all of what is already on the stumpwm wishlist would be included. The general feeling i get from here is, obviously wayland, modularity, multiparadigm and maintainability.... Is there anything from exwm to learn? Or non lisp managers to draw from eg optional defaults, themability etc?

**Comment by sdilts** [comment]
What would the best way to make a feature list? I'm thinking creating a document that we can submit pull requests to in Mahogany or another repository.

**Comment by bijang** [comment]
I guess if you're planning on using mahogany as a base maybe there? Or if you're planning a fresh start maybe elsewhere? 
In terms of contributors would visibility be an issue too? I mean I thought I did a full search of all the wm I could think of including the non sway wayland ones and I had come across paulina... but somehow never heard of mahogony until you brought it up here

**Comment by sdilts** [comment]
It would be nice to work on something in the Stumpwm organization for visibility. @dmb2, could we move the [Mahogany repo](https://github.com/sdilts/mahogany) under the Stumpwm organization or create an empty repo that I have write access to? If not, it's not a problem.

I'll create a document to suggest features later this week.

**Comment by mtlll** [comment]
I too would be interested on helping out with mahogany. I don't have much familiarity with wayland or X11, but I'm quite familiar with the more abstract parts of the Stumpwm codebase and I'm sure I could help with integrating things like command support and other things that don't directly touch the display server part of it. I'm also fairly comfortable in C if we're going that route for the backend stuff. Perhaps something like a shim layer for wlroots in C that makes it easier to set up FFI bindings on the lisp side, would be sufficient.

**Comment by sdilts** [comment]
I just added a file that can be used to collect feature requests. I'm not sure how specific we should be, but it should at least provide a place to figure out what we need to implement, and what pitfalls to watch out for.

You can find it here: https://github.com/sdilts/mahogany/blob/master/doc/devel/features.md

**Comment by dmb2** [comment]
Hi, I'm supportive of moving mahogany (love the name!) to the stumpwm organization.  This will happen with the understanding that once it is moved, it becomes part of the stumpwm family and at the bare minimum will have a functionally similar API and keybindings (much the same way that StumpWM has a significant overlap with ratpoison).

@sdilts If you are willing to make this commitment, we can coordinate moving the repo over in the next few weeks.

**Comment by bijang** [comment]
for what it's worth, seems like theres not much uptake here from interested contributors so probably no big gain to moving to this repo, on the other side, seems like you're in line with stump, so if move and down the line disagree, can always fork.... happy days! my feeling here is, based on brief, subjective, risk benefit, may be worth keeping your autonomy... hope you're all not too affected by the corona bonanza going on!

**Comment by equwal** [comment]
> for what it's worth, seems like theres not much uptake here from interested contributors

I'm interested in this, but not sure given the work required.

> so probably no big gain to moving to this repo, on the other side, seems like you're in line with stump, so if move and down the line disagree, can always fork.... 

I think a Wayland fork could be a good candidate for a "successor" to StumpWM. Maybe other participants will disagree with me on this.

> happy days! my feeling here is, based on brief, subjective, risk benefit, may be worth keeping your autonomy...

No matter what, the X implementation would need to be supported for awhile. Whether that is done by forking a successor or doing it natively is up to whoever is sufficiently motivated for the task.

> hope you're all not too affected by the corona bonanza going on!

Well it has given me more time to write code during mandatory stay-at-home measures, so that is a benefit.

**Comment by sdilts** [comment]
I'm in the process of writing a proof-of-concept for a core written in C with the more interesting functionality implemented in CL. If you want to track my progress or help out, you can find it in the `c-core` branch of mahogany: https://github.com/sdilts/mahogany/tree/c-core/heart. Note that it requires a version of wlroots with the layer-shell branch merged, which you can find here: https://github.com/sdilts/wlroots/tree/0.10.0-layer-shell

**Comment by equwal** [comment]
Very interesting to see how this goes, especially for international users having trouble with xlib and CLX. It seems that a C core is a very good way to go, since CLX doesn't have the kind of resources available to maintain it that it did in 1988. Thanks!

**Comment by bijang** [comment]
This is an interesting discussion, I have been following the next browser development and chanced an email to one of the developers, involved in this discussion you referenced, to draw his attention to mahogony project; he very kindly replied, unfortunately too busy at this time with next and other projects, but I agree theres a lot to draw from and "cross pollination" between these projects.

**Comment by dmb2** [comment]
@sdilts Is there time this weekend we could coordinate transferring mahogany to the stumpwm group? I will add you as a organization member with commit rights to that repository.  I've got some ideas too which would be worth discussing.  I think the whole thing would go easiest over IRC, or some other real time chat.

**Comment by sdilts** [comment]
@dmb2 We could do that this weekend. Sometime this morning would work best, but I'm open all day. Sunday afternoon would work too. #stumpwm on IRC should work fine.

**Comment by dmb2** [comment]
@sdilts I invited you to the organization as a member.  I also forked mahogany to stumpwm.  If you could accept the member invitation and test to see if you have commit access that would be great!

**Comment by sdilts** [comment]
@sdilts I've joined the organization, but I don't have write access. I just figured out you can actually transfer ownership of a project. Should we do that instead of having a fork here?

**Comment by bijang** [comment]
now the repo is moved into the stump organisation I will close this issue

**Comment by dmb2** [comment]
@sdilts Sure, do you know the steps?

**Comment by sdilts** [comment]
Yep. I tried to do it yesterday, but apparently you need to delete the mahogany fork first. After that, you should get a notification that I want to transfer the repo, and accept it.

**Comment by dmb2** [comment]
@sdilts Give that a shot, I'll add you as a maintainer once its in stumpwm

**Comment by sdilts** [comment]
Shoot. I misread the instructions. The steps are:
1. I transfer the repository to you.
2. You transfer it to stumpwm, as you have permission to create a new repository in the organization.

**Comment by dmb2** [comment]
Ah great! Stand by.

**Comment by sdilts** [comment]
Here's the instructions for transferring : https://help.github.com/en/github/administering-a-repository/transferring-a-repository
