### ISSUE TITLE
adopts command system of CLIM

### ISSUE THREAD

**Issue by m-g-r** [stumpwm/stumpwm#779]
I stumbled upon @dmb2 really exciting comment https://github.com/stumpwm/stumpwm/issues/659#issuecomment-574458300 that mentions McCLIM in a sentence:
>  Long-term, I would like to explore using McCLIM for gui elements and piggy back of their text rendering.

@dmb2 hey, that sounds interesting, I was quite active in McCLIM 12 to 15 years ago, contributed some extensions and examples and also worked on Beirc and Climacs, and recently looked a bit into it again. Actually, I was confused by the command system of StumpWM quite a bit because I am more familiar with CLIM and Common Lisp and only wrote a few things for Emacs (e.g. https://github.com/xquery-mode/oook-selector). I'd have expected that the command system of StumpWM would be more like CLIM but it has more an Emacs feeling to it and there are things that are necessary maybe in Emacs Lisp but not in Common Lisp in it. Well, the influence of Emacs is, of course, apparent when you look a the mode-line idea for example.

So, what do you think about adopting the commands and presentations of CLIM?

**Comment by PuercoPop** [comment]
@m-g-r It would be really useful. It is my impression that things like `define-stumpwm-type` are an attempt to emulate CLIM.

**Comment by montaropdf** [comment]
I would also like to see McClim used in StumWM. That framework is intriguing, to say the least. I hope I will have the opportunity to use it soon for a project.

I think there is a opportunity to, somehow, harmonize the UI of the WM. Like merging le input bar and the mode-line into one component, à la emacs. Using McCLIM views to display the various data of the existing contributions leaving the message buffer for the "system" itself.

**Comment by goose121** [comment]
I think it would be really interesting if McCLIM could be used for StumpWM (especially because it would mean that Stump could interact with presentations, etc. of applications running in the same image!), and I'm considering implementing a frame manager that would allow for this (at least I think it would have to be a frame manager, in order to allow it to inject a `stumpwm:window` presentation at the top level of the frames so that accepting entire windows in commands would work)

**Comment by dmb2** [comment]
@m-g-r What I'm about to say may expose my ignorance of McCLIM, but I don't want to just copy the API.  I would like to explore using McCLIM to draw gui elements like the mode-line or input boxes.  If there's a more natural way to expose UI to the user that doesn't involve graphical elements that we can take advantage with McCLIM I'm supportive, but we might have our hands tied with respect to backward compatibility.

**Comment by szos** [comment]
This issue piqued my interest and i threw together a little interactor proof of concept to supplement the colon command. It isnt easily usable as is due to the lack of integration with StumpWM, but its a neat little application with some potential to replace colon, in my opinion. To get started, you can open a repl and evaluate `(stumpwm-interactor::call-interactor)`, or read the beginning of the file and copy/paste the interactor. It can be found here: https://gist.github.com/szos/257ab1b6a4e27dc630647fcf704f4fae

I also threw together a mode line application, which also suffers from lack of integration (although both of these were written in the same day, so integrating might be very easy), but is in my opinion a better mode line than the built in mode line. It is currently set up to display all groups, and all windows for the current group. you can click on a group/window to switch to it. To get started load this gist and evaluate `(stumpwm-modeline::start-mode-line)`. it can be found here: https://gist.github.com/szos/4f567d8263bc80422ae78e2ca5c69f23

Ideally, one could create presentations for windows, frames, groups, heads, etc, in order to supplement keybindings with the mouse. I thought to write a simple mode line as well, but wasnt sure how to integrate it into stumpwm.

**Comment by dmb2** [comment]
@szos Thanks for doing some exploratory work! If you can pull your gists into a module, maybe we can work at a module level to test new gui capabilities, and when things are mature we can merge the modules into stumpwm proper?

**Comment by szos** [comment]
No problem! CLIM is really enjoyable to work with, even if the learning curve is steep. I'll throw the code into a module/asdf system on my own account, should I open a pull request to include it in the contrib repo?
