### ISSUE TITLE
After update from 18.05.94 to 19.11.161, my wall paper is often covered in grey.

### ISSUE THREAD

**Issue by kkatsuyuki** [stumpwm/stumpwm#798]
I updated stumpwm yesterday, but one trouble sometimes occur. See the below image.
![2020-07-12_12-53](https://user-images.githubusercontent.com/23418341/87253336-ffb11300-c43f-11ea-8eee-6a8d8a07f2a3.png)

When the trouble doesn't occur, the screen becomes
![2020-07-12_12-49](https://user-images.githubusercontent.com/23418341/87253396-76e6a700-c440-11ea-98ff-1ab7b88842a9.png)

Is there some measure to resolve this issue?

My Linux OS is arch linux 5.7.7-arch1-1.

**Comment by PuercoPop** [comment]
I'm guessing the behavior is related to this commit https://github.com/stumpwm/stumpwm/commit/3653e59fc869520e42bba09730d6fd646d6d1e89. After this commit StumpWM initializes the background to a color.

Could you be more specific about what you mean by trouble? Is that that sometimes you get one wall paper and sometimes another? If so how are you setting your wallpaper. If using an external program like feh, I'm guessing you are calling it in your `.xinitrc` before calling StumpWM? If that is the case the issue is that which every program sets the background first 'wins'. To en sure that you always get the background you want you can move the call to the external program to your `.stumprc` file. That way that would always happen last.

If the issue is something else could you past the log after passting the following at the start of your `.stumprc` file?

```lisp
(setf *debug-level* 10)
(redirect-all-output (data-dir-file "debug-output.txt"))
```

**Comment by kkatsuyuki** [comment]
As you pointed out, my wallpaper is called in `.xinitrc`. I moved the wallpaper display program to the stumWM config file, and stumpWM doesn't cover the wallpaper.

Thank you very much!
