### ISSUE TITLE
Build fails on latest SBCL 2.2.6.118-bb245ef94

### ISSUE THREAD

**Issue by reltr** [stumpwm/stumpwm#994]
As of [7882c92e6a5d6da86c2acd1242806aa05f0479f8](https://github.com/sbcl/sbcl/commit/856a6ac26f2e7ac74d5f26cd4390bc1bd7e63c4e) SBCL removes the symbol `sb-unix:unix-select` which results in a build failure on stumpwm/ioloop.lisp.
Given the verbiage in the commit, this is not an mistake, and won't be reversed.
This feature is replaced with `sb-unix:unix-simple-poll`, but I do not know how to alter the calls in ioloop.lisp to adapt the code to the new interface.

To reproduce:
1. Build latest SBCL from Git
2. Attempt to build StumpWM from source

Thank you,

**Comment by PuercoPop** [comment]
I have to double check, but iirc sb-unix is considered an 'internal' package and sb-posix is the one we should be using

**Comment by PuercoPop** [comment]
Had some time to look into, there is sb-unix:unix-fast-select which receives the same arguments but returns different values

**Comment by cnoceda** [comment]
Same problem here whit SBCL 2.2.7

**Comment by yusi1** [comment]
Same problem for me, can't build StumpWM anymore, it just fails with that.

**Comment by yusi1** [comment]
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "UNIX-SELECT" not found in the SB-UNIX package.
;   
;       Line: 273, Column: 43, File-Position: 13683
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/yaslam/.gitcloned/stumpwm/ioloop.lisp" {1003E8F223}>
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "UNIX-SELECT" not found in the SB-UNIX package.
;   
;       Line: 273, Column: 43, File-Position: 13683
```

**Comment by jl2** [comment]
I looked into this a little bit earlier this week, and the fix isn't very straightforward.

SBCL removed unix-select, but AFAICT the function they replaced it with in their code, sb-unix:unix-simple-poll, won't work for the way StumpWM is using it because StumpWM is waiting on mulitple file descriptors.

sb-unix:unix-fast-select should work, but the arguments and return values are encoded differently (directly as foreign (struct fd-set)) and when I tried it, StumpWM froze.  I'll have more time to tinker with it this weekend.

In the meantime, I've been using a local branch of SBCL with unix-select added back :-/
